//! Integration tests for `fraiseql generate-client typescript`.
//!
//! The compiled-schema fixture is embedded inline so it is not subject to the
//! repo-wide `*.compiled.json` gitignore rule.
#![allow(clippy::unwrap_used)] // Reason: test code, panics are acceptable

use std::path::Path;

use assert_cmd::Command;

const SCHEMA: &str = r#"{
  "enums": [
    { "name": "Role", "values": [ { "name": "ADMIN" }, { "name": "USER" } ] }
  ],
  "types": [
    {
      "name": "User",
      "sql_source": "v_user",
      "fields": [
        { "name": "id", "field_type": "ID" },
        { "name": "name", "field_type": "String" },
        { "name": "role", "field_type": { "Enum": "Role" } }
      ]
    }
  ],
  "queries": [
    {
      "name": "getUser",
      "return_type": "User",
      "nullable": true,
      "arguments": [ { "name": "id", "arg_type": "ID", "nullable": false } ]
    }
  ],
  "mutations": []
}"#;

fn write_schema(dir: &Path) -> std::path::PathBuf {
    let path = dir.join("schema.compiled.json");
    std::fs::write(&path, SCHEMA).unwrap();
    path
}

#[test]
fn generate_client_typescript_writes_expected_files() {
    let tmp = tempfile::tempdir().unwrap();
    let schema = write_schema(tmp.path());
    let out = tmp.path().join("generated");

    Command::cargo_bin("fraiseql-cli")
        .unwrap()
        .args(["generate-client", "typescript"])
        .arg("--schema")
        .arg(&schema)
        .arg("--out")
        .arg(&out)
        .assert()
        .success();

    for f in ["types.ts", "enums.ts", "queries.ts", "client.ts", "index.ts"] {
        assert!(out.join(f).exists(), "expected generated file {f}");
    }
    // No mutations in this schema → mutations.ts must be skipped, not emitted empty.
    assert!(!out.join("mutations.ts").exists(), "mutations.ts should be skipped");

    let types = std::fs::read_to_string(out.join("types.ts")).unwrap();
    assert!(types.contains("AUTO-GENERATED by fraiseql-codegen"));
    assert!(types.contains("export interface User"));
}

#[test]
fn generate_client_refuses_to_overwrite_without_force() {
    let tmp = tempfile::tempdir().unwrap();
    let schema = write_schema(tmp.path());
    let out = tmp.path().join("generated");

    // First generation succeeds.
    Command::cargo_bin("fraiseql-cli")
        .unwrap()
        .args(["generate-client", "typescript"])
        .arg("--schema")
        .arg(&schema)
        .arg("--out")
        .arg(&out)
        .assert()
        .success();

    // Second without --force is refused.
    Command::cargo_bin("fraiseql-cli")
        .unwrap()
        .args(["generate-client", "typescript"])
        .arg("--schema")
        .arg(&schema)
        .arg("--out")
        .arg(&out)
        .assert()
        .failure();

    // With --force it succeeds again.
    Command::cargo_bin("fraiseql-cli")
        .unwrap()
        .args(["generate-client", "typescript"])
        .arg("--schema")
        .arg(&schema)
        .arg("--out")
        .arg(&out)
        .arg("--force")
        .assert()
        .success();
}

#[test]
fn generate_client_errors_clearly_when_schema_missing() {
    let tmp = tempfile::tempdir().unwrap();
    let out = tmp.path().join("generated");

    Command::cargo_bin("fraiseql-cli")
        .unwrap()
        .args(["generate-client", "typescript"])
        .arg("--schema")
        .arg(tmp.path().join("does-not-exist.json"))
        .arg("--out")
        .arg(&out)
        .assert()
        .failure();
}
