from dataclasses import dataclass
from typing import Any, Optional

@dataclass
class UserContext:
    user_id: str
    email: Optional[str]
    name: Optional[str]
    roles: list[str]
    permissions: list[str]
    metadata: dict[str, Any]

class AuthProvider:
    async def authenticate(self, token: str) -> UserContext: ...
    async def validate_token(self, token: str) -> bool: ...

@dataclass
class Auth0Config:
    domain: str
    api_identifier: str
    client_id: Optional[str]
    client_secret: Optional[str]

class Auth0Provider(AuthProvider):
    def __init__(self, config: Auth0Config) -> None: ...
    async def authenticate(self, token: str) -> UserContext: ...

class Auth0ProviderWithRevocation(AuthProvider):
    async def authenticate(self, token: str) -> UserContext: ...

def requires_auth(fn: Any) -> Any: ...
def requires_role(role: str) -> Any: ...
def requires_permission(permission: str) -> Any: ...
@dataclass
class RevocationConfig:
    store_type: str
    check_interval: int
    cache_ttl: int

class InMemoryRevocationStore:
    async def add_revoked_token(self, token: str, expiry: Optional[int] = None) -> None: ...
    async def is_revoked(self, token: str) -> bool: ...

class PostgreSQLRevocationStore:
    async def add_revoked_token(self, token: str, expiry: Optional[int] = None) -> None: ...
    async def is_revoked(self, token: str) -> bool: ...

class TokenRevocationMixin:
    async def revoke_token(self, token: str) -> None: ...
    async def is_token_revoked(self, token: str) -> bool: ...

class TokenRevocationService:
    async def revoke(self, token: str) -> None: ...
    async def is_revoked(self, token: str) -> bool: ...
    async def cleanup_expired(self) -> int: ...
