// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: e3689c831ba45b28a4bf02ecf33ad401b9a4fa93ebdc466fb91244bd09a13d29
// fraiseql-codegen: 2.4.0

/** Authorization role granted to a user. */
export type UserRole = "ADMIN" | "EDITOR" | "VIEWER";
