// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: 5aa17830eb4874e39a967f99b8cb0dc9db2a09099c4f13687c562f65d94af049
// fraiseql-codegen: 2.15.0

/** Authorization role granted to a user. */
export type UserRole = "ADMIN" | "EDITOR" | "VIEWER";
