// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: cadb4520b6c0bf261db52834561322e2fb2de06b17d3e0f34ee6d2cada558c0e
// fraiseql-codegen: 2.15.0

/** Authorization role granted to a user. */
export type UserRole = "ADMIN" | "EDITOR" | "VIEWER";
