// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: e3689c831ba45b28a4bf02ecf33ad401b9a4fa93ebdc466fb91244bd09a13d29
// fraiseql-codegen: 2.4.0

import type { UserRole } from "./enums";

/** Fields required to create a user. */
export interface CreateUserInput {
  email: string;
  displayName?: string | null;
  role: UserRole;
}

export interface UpdateUserInput {
  displayName?: string | null;
  role?: UserRole | null;
}

/** Filter criteria for listing users. */
export interface UserFilter {
  email?: string | null;
  role?: UserRole | null;
  tags?: string[] | null;
}
