// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: cadb4520b6c0bf261db52834561322e2fb2de06b17d3e0f34ee6d2cada558c0e
// fraiseql-codegen: 2.15.0

import type { UserRole } from "./enums";

/** Fields required to create a user. */
export interface CreateUserInput {
  email: string;
  displayName?: string | null;
  role: UserRole;
}

export interface UpdateUserInput {
  displayName?: string | null;
  role?: UserRole | null;
}

/** Filter criteria for listing users. */
export interface UserFilter {
  email?: string | null;
  role?: UserRole | null;
  tags?: string[] | null;
}
