// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: 46c1a4f5d4149c3e4e0bb4116a1c23e668cf11b54d8a4e7db7122a2f3d4bef25
// fraiseql-codegen: 2.3.2

import type { UserRole } from "./enums";

/** Fields required to create a user. */
export interface CreateUserInput {
  email: string;
  displayName?: string | null;
  role: UserRole;
}

export interface UpdateUserInput {
  displayName?: string | null;
  role?: UserRole | null;
}

/** Filter criteria for listing users. */
export interface UserFilter {
  email?: string | null;
  role?: UserRole | null;
  tags?: string[] | null;
}
