// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: e3689c831ba45b28a4bf02ecf33ad401b9a4fa93ebdc466fb91244bd09a13d29
// fraiseql-codegen: 2.4.0

import { FraiseqlClient } from "./client";
import type { CreateUserInput, UpdateUserInput } from "./inputs";
import type { CreateUserResult, User } from "./types";

export type ErrorTypename = "EmailTakenError";

const ERROR_TYPENAMES: ReadonlySet<string> = new Set<string>(["EmailTakenError"]);

/** Narrow a mutation result union to its typed-error members. */
export function isErrorResult<T extends { __typename: string }>(
  value: T,
): value is Extract<T, { __typename: ErrorTypename }> {
  return ERROR_TYPENAMES.has(value.__typename);
}

/** Create a user; returns the user or a typed error. */
const CREATE_USER = `mutation createUser($input: CreateUserInput!) {
  createUser(input: $input) {
    __typename
    ... on User {
      id
      email
      displayName
      role
      createdAt
    }
    ... on EmailTakenError {
      message
      attemptedEmail
      existingUserId
    }
  }
}`;

export async function createUser(
  client: FraiseqlClient,
  variables: { input: CreateUserInput },
): Promise<CreateUserResult> {
  const data = await client.request<{ createUser: CreateUserResult }>(CREATE_USER, variables);
  return data.createUser;
}

/** Update a user's mutable fields. */
const UPDATE_USER = `mutation updateUser($id: ID!, $input: UpdateUserInput!) {
  updateUser(id: $id, input: $input) {
    __typename
    id
    email
    displayName
    role
    createdAt
  }
}`;

export async function updateUser(
  client: FraiseqlClient,
  variables: { id: string; input: UpdateUserInput },
): Promise<User> {
  const data = await client.request<{ updateUser: User }>(UPDATE_USER, variables);
  return data.updateUser;
}

/** Delete a user by id. */
const DELETE_USER = `mutation deleteUser($id: ID!) {
  deleteUser(id: $id) {
    __typename
    id
    email
    displayName
    role
    createdAt
  }
}`;

export async function deleteUser(
  client: FraiseqlClient,
  variables: { id: string },
): Promise<User> {
  const data = await client.request<{ deleteUser: User }>(DELETE_USER, variables);
  return data.deleteUser;
}
