// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: 5aa17830eb4874e39a967f99b8cb0dc9db2a09099c4f13687c562f65d94af049
// fraiseql-codegen: 2.15.0

import { FraiseqlClient } from "./client";
import type { UserFilter } from "./inputs";
import type { Connection, Post, User } from "./types";

/** Fetch a single user by id. */
const GET_USER = `query getUser($id: ID!) {
  getUser(id: $id) {
    __typename
    id
    email
    displayName
    role
    createdAt
  }
}`;

export async function getUser(
  client: FraiseqlClient,
  variables: { id: string },
): Promise<User | null> {
  const data = await client.request<{ getUser: User | null }>(GET_USER, variables);
  return data.getUser;
}

/** List users, optionally filtered. */
const USERS = `query users($filter: UserFilter, $orderBy: JSON, $limit: Int, $offset: Int) {
  users(filter: $filter, orderBy: $orderBy, limit: $limit, offset: $offset) {
    __typename
    id
    email
    displayName
    role
    createdAt
  }
}`;

export async function users(
  client: FraiseqlClient,
  variables: { filter?: UserFilter | null; orderBy?: unknown | null; limit?: number | null; offset?: number | null } = {},
): Promise<User[]> {
  const data = await client.request<{ users: User[] }>(USERS, variables);
  return data.users;
}

/** Relay-style paginated posts. */
const POSTS_CONNECTION = `query postsConnection($first: Int, $after: String) {
  postsConnection(first: $first, after: $after) {
    edges {
      cursor
      node {
        __typename
        id
        title
        body
        published
        viewCount
        score
        metadata
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}`;

export async function postsConnection(
  client: FraiseqlClient,
  variables: { first?: number; after?: string } = {},
): Promise<Connection<Post>> {
  const data = await client.request<{ postsConnection: Connection<Post> }>(POSTS_CONNECTION, variables);
  return data.postsConnection;
}
