// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: 46c1a4f5d4149c3e4e0bb4116a1c23e668cf11b54d8a4e7db7122a2f3d4bef25
// fraiseql-codegen: 2.3.2

import { FraiseqlClient } from "./client";
import type { UserFilter } from "./inputs";
import type { Connection, Post, User } from "./types";

/** Fetch a single user by id. */
const GET_USER = `query getUser($id: ID!) {
  getUser(id: $id) {
    __typename
    id
    email
    displayName
    role
    createdAt
  }
}`;

export async function getUser(
  client: FraiseqlClient,
  variables: { id: string },
): Promise<User | null> {
  const data = await client.request<{ getUser: User | null }>(GET_USER, variables);
  return data.getUser;
}

/** List users, optionally filtered. */
const USERS = `query users($filter: UserFilter) {
  users(filter: $filter) {
    __typename
    id
    email
    displayName
    role
    createdAt
  }
}`;

export async function users(
  client: FraiseqlClient,
  variables: { filter?: UserFilter | null } = {},
): Promise<User[]> {
  const data = await client.request<{ users: User[] }>(USERS, variables);
  return data.users;
}

/** Relay-style paginated posts. */
const POSTS_CONNECTION = `query postsConnection($first: Int, $after: String) {
  postsConnection(first: $first, after: $after) {
    edges {
      cursor
      node {
        __typename
        id
        title
        body
        published
        viewCount
        score
        metadata
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}`;

export async function postsConnection(
  client: FraiseqlClient,
  variables: { first?: number; after?: string } = {},
): Promise<Connection<Post>> {
  const data = await client.request<{ postsConnection: Connection<Post> }>(POSTS_CONNECTION, variables);
  return data.postsConnection;
}
