// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: 5aa17830eb4874e39a967f99b8cb0dc9db2a09099c4f13687c562f65d94af049
// fraiseql-codegen: 2.15.0

export type RelationshipCardinality = "oneToMany" | "manyToOne" | "oneToOne";

export interface RelationshipMeta {
  targetType: string;
  cardinality: RelationshipCardinality;
  foreignKey: string;
  referencedKey: string;
}

export const relationships = {
  User: {
    tenant: { targetType: "Tenant", cardinality: "manyToOne", foreignKey: "fk_tenant", referencedKey: "id" },
    posts: { targetType: "Post", cardinality: "oneToMany", foreignKey: "fk_author", referencedKey: "id" },
  },
  Post: {
    author: { targetType: "User", cardinality: "manyToOne", foreignKey: "fk_author", referencedKey: "id" },
    comments: { targetType: "Comment", cardinality: "oneToMany", foreignKey: "fk_post", referencedKey: "id" },
  },
} as const;

export type EntityRelationships = typeof relationships;
