// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: a398cd5f87f2b028b83450214f75fd6827f581f42251d9c929e016506c4eb5e4
// fraiseql-codegen: 2.5.0

export type RelationshipCardinality = "oneToMany" | "manyToOne" | "oneToOne";

export interface RelationshipMeta {
  targetType: string;
  cardinality: RelationshipCardinality;
  foreignKey: string;
  referencedKey: string;
}

export const relationships = {
  User: {
    tenant: { targetType: "Tenant", cardinality: "manyToOne", foreignKey: "fk_tenant", referencedKey: "id" },
    posts: { targetType: "Post", cardinality: "oneToMany", foreignKey: "fk_author", referencedKey: "id" },
  },
  Post: {
    author: { targetType: "User", cardinality: "manyToOne", foreignKey: "fk_author", referencedKey: "id" },
    comments: { targetType: "Comment", cardinality: "oneToMany", foreignKey: "fk_post", referencedKey: "id" },
  },
} as const;

export type EntityRelationships = typeof relationships;
