// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: cadb4520b6c0bf261db52834561322e2fb2de06b17d3e0f34ee6d2cada558c0e
// fraiseql-codegen: 2.15.0

export type RelationshipCardinality = "oneToMany" | "manyToOne" | "oneToOne";

export interface RelationshipMeta {
  targetType: string;
  cardinality: RelationshipCardinality;
  foreignKey: string;
  referencedKey: string;
}

export const relationships = {
  User: {
    tenant: { targetType: "Tenant", cardinality: "manyToOne", foreignKey: "fk_tenant", referencedKey: "id" },
    posts: { targetType: "Post", cardinality: "oneToMany", foreignKey: "fk_author", referencedKey: "id" },
  },
  Post: {
    author: { targetType: "User", cardinality: "manyToOne", foreignKey: "fk_author", referencedKey: "id" },
    comments: { targetType: "Comment", cardinality: "oneToMany", foreignKey: "fk_post", referencedKey: "id" },
  },
} as const;

export type EntityRelationships = typeof relationships;
