// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.
// schema-hash: 5aa17830eb4874e39a967f99b8cb0dc9db2a09099c4f13687c562f65d94af049
// fraiseql-codegen: 2.15.0

import type { UserRole } from "./enums";

export interface PageInfo {
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  startCursor: string | null;
  endCursor: string | null;
}

export interface Edge<T> {
  cursor: string;
  node: T;
}

export interface Connection<T> {
  edges: Edge<T>[];
  pageInfo: PageInfo;
  totalCount?: number;
}

/** An object with a globally unique ID. */
export interface Node {
  __typename: string;
  id: string;
}

/** A billing/isolation boundary that owns users and posts. */
export interface Tenant extends Node {
  __typename: "Tenant";
  id: string;
  name: string;
}

/** A person who can author posts. */
export interface User extends Node {
  __typename: "User";
  id: string;
  email: string;
  /** Optional human-friendly name. */
  displayName: string | null;
  role: UserRole;
  createdAt: string;
}

/** A piece of content authored by a user. */
export interface Post extends Node {
  __typename: "Post";
  id: string;
  title: string;
  body: string;
  published: boolean;
  viewCount: number;
  score: number | null;
  metadata: unknown | null;
}

/** A reader's comment on a post. */
export interface Comment {
  __typename: "Comment";
  id: string;
  body: string;
}

/** Returned when a mutation is rejected because the email is already in use. */
export interface EmailTakenError {
  __typename: "EmailTakenError";
  /** Error class injected by the mutation runtime (the `error_class`). */
  status: string;
  message: string;
  attemptedEmail: string;
  existingUserId: string;
}

/** Either the created user or a typed error. */
export type CreateUserResult = User | EmailTakenError;
