#![no_main]

//! Fuzz the JSON parse path that JSONB rows take after they come off the
//! Postgres wire (F030).
//!
//! `fraiseql_wire::stream::parse_json` consumes the JSON bytes extracted from
//! a `DataRow` and feeds them through `serde_json::from_slice`. Every
//! variable JSON body that the GraphQL server sees crosses this entry point
//! eventually, so any panic, OOM, or stack overflow here is a denial-of-
//! service vector.
//!
//! The fuzz target exercises both the "raw bytes" path and the
//! "JSON-wrapped-in-protocol-frame" path so that structured-corpus inputs
//! generated by libfuzzer hit both `extract_json_bytes` and `parse_json`.

use bytes::Bytes;
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    // Direct parse: feed arbitrary bytes through `parse_json`. The function
    // is supposed to return `Err(_)` for any invalid JSON without panicking
    // or recursing unboundedly. Stack depth, integer overflow, control-
    // character handling, and surrogate pairs in strings are the interesting
    // cases libfuzzer is good at finding.
    let bytes = Bytes::copy_from_slice(data);
    let _ = fraiseql_wire::stream::parse_json(bytes);
});
