[project]
name = "todo-api"
version = "0.1.0"
description = "A minimal FraiseQL Todo API"
requires-python = ">=3.10"
dependencies = [
    "fraiseql>=0.2.1",
    "uvicorn>=0.34.3",
    "python-dotenv>=1.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.21.0",
    "ruff>=0.8.4",
]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "strict"
