# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
    # Rust is part of the build for fraiseql_rs extension
    rust: latest
  # Required for Rust compilation
  apt_packages:
    - pkg-config
    - libssl-dev

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build on PR previews for documentation changes
build-on-pull-requests: true

# Optionally build PDF & ePub
formats:
  - pdf
  - epub
