-- Auto-generated Arrow view DDL
-- Entity: User
-- View: ta_test
-- Type: Table Arrow (ta_)
-- Refresh strategy: trigger-based
-- Generated by: fraiseql generate-views

DROP VIEW IF EXISTS ta_test CASCADE;

CREATE VIEW ta_test AS
SELECT
    id,
    -- User entity fields optimized for Arrow
    created_at,
    updated_at
FROM public.schema_placeholder
WHERE archived_at IS NULL
ORDER BY id;

-- Composition views
CREATE VIEW test_recent AS
SELECT * FROM {}
WHERE updated_at > NOW() - INTERVAL '7 days'
ORDER BY updated_at DESC;

CREATE VIEW test_count AS
SELECT COUNT(*) as total FROM {};

-- Monitoring functions
CREATE OR REPLACE FUNCTION monitor_ta_test()
RETURNS TABLE (
    metric_name TEXT,
    metric_value BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 'row_count'::TEXT, COUNT(*)::BIGINT FROM ta_test;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
