//! Python client generator.
//!
//! `generate(&CompiledSchema)` returns a [`Generated`] map of Python files
//! implementing a typed, standard-library-only client for **Python ≥ 3.12**.
//! The `GraphQL` documents come from `client::common` and are byte-identical to
//! the `TypeScript` generator's; this module owns the Python packaging: which
//! files exist, the header stamp, and the `__init__.py` re-exports.

mod emit;
mod render;
mod runtime;

use std::path::PathBuf;

use fraiseql_core::schema::CompiledSchema;

pub(super) use super::common::SchemaCtx as Ctx;
use crate::{Generated, Result};

/// Generate a Python client from a compiled schema.
///
/// Returns a map of relative path → file content. Conditional files
/// (`enums.py`, `inputs.py`, `mutations.py`, `relationships.py`) are present
/// only when the schema has the corresponding definitions; `__init__.py`
/// re-exports exactly the files that were emitted.
///
/// # Errors
///
/// Returns an error if the schema cannot be hashed for stamping (see
/// [`crate::client::schema_hash`]).
pub fn generate(schema: &CompiledSchema) -> Result<Generated> {
    let ctx = Ctx::new(schema);
    let hash = super::schema_hash(schema)?;

    let mut files = Generated::new();
    let mut modules: Vec<&str> = Vec::new();
    let add = |files: &mut Generated,
               modules: &mut Vec<&'static str>,
               name: &'static str,
               body: String| {
        files.insert(PathBuf::from(format!("{name}.py")), stamp(&body, &hash));
        modules.push(name);
    };

    // `client` first so `__init__.py` exports the runtime before the modules
    // that import from it.
    add(&mut files, &mut modules, "client", runtime::CLIENT_PY.to_string());
    add(&mut files, &mut modules, "types", emit::types(&ctx));

    if !schema.enums.is_empty() {
        add(&mut files, &mut modules, "enums", emit::enums(schema));
    }
    if !schema.input_types.is_empty() {
        add(&mut files, &mut modules, "inputs", emit::inputs(&ctx));
    }
    if !schema.queries.is_empty() {
        add(&mut files, &mut modules, "queries", emit::queries(&ctx));
    }
    if !schema.mutations.is_empty() {
        add(&mut files, &mut modules, "mutations", emit::mutations(&ctx));
    }
    if ctx.has_relationships {
        add(&mut files, &mut modules, "relationships", emit::relationships(schema));
    }

    files.insert(PathBuf::from("__init__.py"), stamp(&emit::init(&modules), &hash));

    Ok(files)
}

/// Prepend the auto-generated header (with the schema hash) to a file body.
///
/// `# ruff: noqa` keeps a consumer's linter out of generated code (operation
/// names mirror the `GraphQL` schema's casing, star re-exports are deliberate);
/// type checkers still see everything.
fn stamp(body: &str, hash: &str) -> String {
    format!(
        "# AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n# schema-hash: {hash}\n# fraiseql-codegen: {version}\n# Requires Python >= 3.12.\n# ruff: noqa\n\n{body}",
        version = env!("CARGO_PKG_VERSION"),
    )
}

#[cfg(test)]
mod tests;
