//! Tests for the Python client generator.
//!
//! Structural assertions on the emitted files. The cross-language guarantee —
//! that the `GraphQL` documents are byte-identical in every generated client —
//! is a claim about all the generators at once and lives in `client::tests`. The
//! "does the output type-check" direction runs in CI (`sdk-conformance.yml`
//! generates from the canonical conformance fixture and runs `ty`/`tsc` on the
//! output).

#![allow(clippy::unwrap_used, clippy::panic)] // Reason: test code, panics are acceptable

use std::path::PathBuf;

use fraiseql_core::schema::{
    ArgumentDefinition, CompiledSchema, EnumDefinition, EnumValueDefinition, FieldDefinition,
    FieldType, InputFieldDefinition, InputObjectDefinition, MutationDefinition, QueryDefinition,
    TypeDefinition,
};

use super::{generate, render::field_type_py};

fn fixture() -> CompiledSchema {
    let mut schema = CompiledSchema::new();

    let mut user = TypeDefinition::new("User", "v_user");
    user.fields.push(FieldDefinition::new("id", FieldType::Id));
    user.fields.push(FieldDefinition::new("email", FieldType::String));
    let mut age = FieldDefinition::new("age", FieldType::Int);
    age.nullable = true;
    user.fields.push(age);
    user.fields
        .push(FieldDefinition::new("role", FieldType::Enum("UserRole".to_string())));
    schema.types.push(user);

    let mut not_found = TypeDefinition::new("NotFoundError", "");
    not_found.is_error = true;
    not_found.fields.push(FieldDefinition::new("message", FieldType::String));
    schema.types.push(not_found);

    schema.enums.push(EnumDefinition {
        name:        "UserRole".to_string(),
        values:      vec![
            EnumValueDefinition {
                name:        "ADMIN".to_string(),
                description: None,
                deprecation: None,
            },
            EnumValueDefinition {
                name:        "MEMBER".to_string(),
                description: None,
                deprecation: None,
            },
        ],
        description: None,
    });

    schema
        .input_types
        .push(InputObjectDefinition::new("CreateUserInput").with_fields(vec![
            InputFieldDefinition::new("email", "String!"),
            InputFieldDefinition::new("role", "UserRole"),
        ]));

    let mut get_user = QueryDefinition::new("getUser", "User");
    get_user.nullable = true;
    get_user.arguments.push(ArgumentDefinition::new("id", FieldType::Id));
    schema.queries.push(get_user);

    let mut users = QueryDefinition::new("users", "User").returning_list();
    let mut limit = ArgumentDefinition::new("limit", FieldType::Int);
    limit.nullable = true;
    users.arguments.push(limit);
    schema.queries.push(users);

    let mut relay = QueryDefinition::new("usersConnection", "User");
    relay.relay = true;
    schema.queries.push(relay);

    let mut create = MutationDefinition::new("createUser", "User");
    create.arguments.push(ArgumentDefinition::new(
        "input",
        FieldType::Input("CreateUserInput".to_string()),
    ));
    schema.mutations.push(create);

    schema
}

fn file(files: &crate::Generated, name: &str) -> String {
    files
        .get(&PathBuf::from(name))
        .unwrap_or_else(|| panic!("missing generated file {name}"))
        .clone()
}

#[test]
fn emits_the_expected_files() {
    let files = generate(&fixture()).unwrap();
    for name in [
        "client.py",
        "types.py",
        "enums.py",
        "inputs.py",
        "queries.py",
        "mutations.py",
        "__init__.py",
    ] {
        assert!(files.contains_key(&PathBuf::from(name)), "missing {name}");
    }
    // No relationships in the fixture → no relationships.py.
    assert!(!files.contains_key(&PathBuf::from("relationships.py")));
}

#[test]
fn every_file_is_stamped_with_the_schema_hash() {
    let files = generate(&fixture()).unwrap();
    for (path, content) in &files {
        assert!(
            content
                .starts_with("# AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n# schema-hash: "),
            "{} is missing the stamp",
            path.display()
        );
    }
}

#[test]
fn objects_are_typed_dicts_with_literal_typename() {
    let types = file(&generate(&fixture()).unwrap(), "types.py");
    assert!(types.contains("class User(TypedDict):"), "{types}");
    assert!(types.contains("__typename: Literal[\"User\"]"), "{types}");
    assert!(types.contains("age: int | None"), "nullable field must be `| None`: {types}");
    assert!(
        types.contains("from .enums import UserRole"),
        "enum leaf refs must be imported: {types}"
    );
}

#[test]
fn error_type_carries_the_injected_status_field() {
    let types = file(&generate(&fixture()).unwrap(), "types.py");
    let error_block = types.split("class NotFoundError").nth(1).expect("NotFoundError emitted");
    assert!(
        error_block.contains("status: str"),
        "error types must carry the runtime-injected status: {types}"
    );
}

#[test]
fn enums_are_literal_aliases() {
    let enums = file(&generate(&fixture()).unwrap(), "enums.py");
    assert!(enums.contains("type UserRole = Literal[\"ADMIN\", \"MEMBER\"]"), "{enums}");
}

#[test]
fn optional_input_fields_are_not_required() {
    let inputs = file(&generate(&fixture()).unwrap(), "inputs.py");
    assert!(inputs.contains("email: str"), "{inputs}");
    assert!(inputs.contains("role: NotRequired[UserRole | None]"), "{inputs}");
}

#[test]
fn required_args_build_a_plain_variables_dict() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.py");
    assert!(queries.contains("def getUser("), "{queries}");
    assert!(queries.contains("    id: str,"), "{queries}");
    assert!(queries.contains(") -> User | None:"), "{queries}");
    assert!(
        queries.contains("variables = {\"id\": id}"),
        "required-only args must not pass through omit_none: {queries}"
    );
}

#[test]
fn optional_args_are_omitted_when_none() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.py");
    assert!(queries.contains("limit: int | None = None,"), "{queries}");
    assert!(
        queries.contains("variables = omit_none({\"limit\": limit})"),
        "optional args must be dropped when None: {queries}"
    );
}

#[test]
fn relay_queries_paginate_and_return_a_connection() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.py");
    assert!(queries.contains("first: int | None = None,"), "{queries}");
    assert!(queries.contains("after: str | None = None,"), "{queries}");
    assert!(queries.contains(") -> Connection[User]:"), "{queries}");
    let types = file(&generate(&fixture()).unwrap(), "types.py");
    assert!(types.contains("class Connection[T](TypedDict):"), "{types}");
}

#[test]
fn mutations_expose_the_error_guard() {
    let mutations = file(&generate(&fixture()).unwrap(), "mutations.py");
    assert!(
        mutations.contains("type ErrorTypename = Literal[\"NotFoundError\"]"),
        "{mutations}"
    );
    assert!(mutations.contains("def is_error_result("), "{mutations}");
    assert!(mutations.contains("def createUser("), "{mutations}");
}

/// A field or argument named after a Python keyword must not produce a syntax
/// error: fields fall back to the functional `TypedDict` form, parameters get a
/// trailing underscore — while the wire name stays the original.
#[test]
fn python_keywords_are_escaped_without_changing_the_wire_shape() {
    let mut schema = CompiledSchema::new();
    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    thing.fields.push(FieldDefinition::new("import", FieldType::String));
    schema.types.push(thing);
    let mut q = QueryDefinition::new("things", "Thing").returning_list();
    q.arguments.push(ArgumentDefinition::new("from", FieldType::String));
    schema.queries.push(q);

    let files = generate(&schema).unwrap();
    let types = file(&files, "types.py");
    assert!(
        types.contains("Thing = TypedDict("),
        "keyword field must force the functional form: {types}"
    );
    assert!(types.contains("\"import\": str"), "{types}");

    let queries = file(&files, "queries.py");
    assert!(queries.contains("from_: str,"), "keyword param must be escaped: {queries}");
    assert!(
        queries.contains("variables = {\"from\": from_}"),
        "the wire key must stay the original GraphQL name: {queries}"
    );
    // The document itself uses the GraphQL name, untouched.
    assert!(queries.contains("$from: String!"), "{queries}");
}

/// Every pgvector field type renders as the surface it actually has (#959).
///
/// The wildcard arm in `field_type_py` exists to keep a future `#[non_exhaustive]`
/// scalar compiling, and that is exactly what let `HalfVector` and `SparseVector`
/// degrade to `Any` when they were added: the generator kept building, the generated
/// client kept passing `ty`, and a caller's embedding lost its type.
#[test]
fn every_vector_type_maps_to_its_own_surface() {
    // `[Float!]!` in GraphQL, whatever the column's precision.
    assert_eq!(field_type_py(&FieldType::Vector), "list[float]");
    assert_eq!(field_type_py(&FieldType::HalfVector), "list[float]");
    // Each of these is a string in its own text form: a run of 0/1 for a bit
    // vector, `{1:0.5,7:0.25}/1000` for a sparse one.
    assert_eq!(field_type_py(&FieldType::BitVector), "str");
    assert_eq!(field_type_py(&FieldType::SparseVector), "str");
}
