//! Tests for the Python client generator.
//!
//! Structural assertions on the emitted files. The cross-language guarantee —
//! that the `GraphQL` documents are byte-identical in every generated client —
//! is a claim about all the generators at once and lives in `client::tests`. The
//! "does the output type-check" direction runs in CI (`sdk-conformance.yml`
//! generates from the canonical conformance fixture and runs `ty`/`tsc` on the
//! output).

#![allow(clippy::unwrap_used, clippy::panic)] // Reason: test code, panics are acceptable

use std::path::PathBuf;

use fraiseql_core::schema::{
    ArgumentDefinition, CompiledSchema, EnumDefinition, EnumValueDefinition, FieldDefinition,
    FieldType, InputFieldDefinition, InputObjectDefinition, MutationDefinition, QueryDefinition,
    TypeDefinition,
};

use super::{generate, render::field_type_py};

fn fixture() -> CompiledSchema {
    let mut schema = CompiledSchema::new();

    let mut user = TypeDefinition::new("User", "v_user");
    user.fields.push(FieldDefinition::new("id", FieldType::Id));
    user.fields.push(FieldDefinition::new("email", FieldType::String));
    let mut age = FieldDefinition::new("age", FieldType::Int);
    age.nullable = true;
    user.fields.push(age);
    user.fields
        .push(FieldDefinition::new("role", FieldType::Enum("UserRole".to_string())));
    schema.types.push(user);

    let mut not_found = TypeDefinition::new("NotFoundError", "");
    not_found.is_error = true;
    not_found.fields.push(FieldDefinition::new("message", FieldType::String));
    schema.types.push(not_found);

    schema.enums.push(EnumDefinition {
        name:        "UserRole".to_string(),
        values:      vec![
            EnumValueDefinition {
                name:        "ADMIN".to_string(),
                description: None,
                deprecation: None,
            },
            EnumValueDefinition {
                name:        "MEMBER".to_string(),
                description: None,
                deprecation: None,
            },
        ],
        description: None,
    });

    schema
        .input_types
        .push(InputObjectDefinition::new("CreateUserInput").with_fields(vec![
            InputFieldDefinition::new("email", "String!"),
            InputFieldDefinition::new("role", "UserRole"),
        ]));

    let mut get_user = QueryDefinition::new("getUser", "User");
    get_user.nullable = true;
    get_user.arguments.push(ArgumentDefinition::new("id", FieldType::Id));
    schema.queries.push(get_user);

    let mut users = QueryDefinition::new("users", "User").returning_list();
    let mut limit = ArgumentDefinition::new("limit", FieldType::Int);
    limit.nullable = true;
    users.arguments.push(limit);
    schema.queries.push(users);

    let mut relay = QueryDefinition::new("usersConnection", "User");
    relay.relay = true;
    schema.queries.push(relay);

    let mut create = MutationDefinition::new("createUser", "User");
    create.arguments.push(ArgumentDefinition::new(
        "input",
        FieldType::Input("CreateUserInput".to_string()),
    ));
    schema.mutations.push(create);

    schema
}

fn file(files: &crate::Generated, name: &str) -> String {
    files
        .get(&PathBuf::from(name))
        .unwrap_or_else(|| panic!("missing generated file {name}"))
        .clone()
}

#[test]
fn emits_the_expected_files() {
    let files = generate(&fixture()).unwrap();
    for name in [
        "client.py",
        "types.py",
        "enums.py",
        "inputs.py",
        "queries.py",
        "mutations.py",
        "__init__.py",
    ] {
        assert!(files.contains_key(&PathBuf::from(name)), "missing {name}");
    }
    // No relationships in the fixture → no relationships.py.
    assert!(!files.contains_key(&PathBuf::from("relationships.py")));
}

#[test]
fn every_file_is_stamped_with_the_schema_hash() {
    let files = generate(&fixture()).unwrap();
    for (path, content) in &files {
        assert!(
            content
                .starts_with("# AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n# schema-hash: "),
            "{} is missing the stamp",
            path.display()
        );
    }
}

/// Object types carry their `__typename` discriminant and their field types.
///
/// The functional `TypedDict("User", {...})` form is not incidental here: every
/// object type declares `__typename`, which the class syntax would mangle to
/// `_User__typename` (#1033), so object types are always emitted this way.
#[test]
fn objects_are_typed_dicts_with_literal_typename() {
    let types = file(&generate(&fixture()).unwrap(), "types.py");
    assert!(types.contains("User = TypedDict("), "{types}");
    assert!(types.contains("\"__typename\": Literal[\"User\"]"), "{types}");
    assert!(
        types.contains("\"age\": int | None"),
        "nullable field must be `| None`: {types}"
    );
    assert!(
        types.contains("from .enums import UserRole"),
        "enum leaf refs must be imported: {types}"
    );
}

#[test]
fn error_type_carries_the_injected_status_field() {
    let types = file(&generate(&fixture()).unwrap(), "types.py");
    let error_block =
        types.split("NotFoundError = TypedDict").nth(1).expect("NotFoundError emitted");
    assert!(
        error_block.contains("\"status\": str"),
        "error types must carry the runtime-injected status: {types}"
    );
}

#[test]
fn enums_are_literal_aliases() {
    let enums = file(&generate(&fixture()).unwrap(), "enums.py");
    assert!(enums.contains("type UserRole = Literal[\"ADMIN\", \"MEMBER\"]"), "{enums}");
}

#[test]
fn optional_input_fields_are_not_required() {
    let inputs = file(&generate(&fixture()).unwrap(), "inputs.py");
    assert!(inputs.contains("email: str"), "{inputs}");
    assert!(inputs.contains("role: NotRequired[UserRole | None]"), "{inputs}");
}

#[test]
fn required_args_build_a_plain_variables_dict() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.py");
    assert!(queries.contains("def getUser("), "{queries}");
    assert!(queries.contains("    id: str,"), "{queries}");
    assert!(queries.contains(") -> User | None:"), "{queries}");
    assert!(
        queries.contains("variables = {\"id\": id}"),
        "required-only args must not pass through omit_none: {queries}"
    );
}

#[test]
fn optional_args_are_omitted_when_none() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.py");
    assert!(queries.contains("limit: int | None = None,"), "{queries}");
    assert!(
        queries.contains("variables = omit_none({\"limit\": limit})"),
        "optional args must be dropped when None: {queries}"
    );
}

#[test]
fn relay_queries_paginate_and_return_a_connection() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.py");
    assert!(queries.contains("first: int | None = None,"), "{queries}");
    assert!(queries.contains("after: str | None = None,"), "{queries}");
    assert!(queries.contains(") -> Connection[User]:"), "{queries}");
    let types = file(&generate(&fixture()).unwrap(), "types.py");
    assert!(types.contains("class Connection[T](TypedDict):"), "{types}");
}

#[test]
fn mutations_expose_the_error_guard() {
    let mutations = file(&generate(&fixture()).unwrap(), "mutations.py");
    assert!(
        mutations.contains("type ErrorTypename = Literal[\"NotFoundError\"]"),
        "{mutations}"
    );
    assert!(mutations.contains("def is_error_result("), "{mutations}");
    assert!(mutations.contains("def createUser("), "{mutations}");
}

/// A field or argument named after a Python keyword must not produce a syntax
/// error: fields fall back to the functional `TypedDict` form, parameters get a
/// trailing underscore — while the wire name stays the original.
#[test]
fn python_keywords_are_escaped_without_changing_the_wire_shape() {
    let mut schema = CompiledSchema::new();
    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    thing.fields.push(FieldDefinition::new("import", FieldType::String));
    schema.types.push(thing);
    let mut q = QueryDefinition::new("things", "Thing").returning_list();
    q.arguments.push(ArgumentDefinition::new("from", FieldType::String));
    schema.queries.push(q);

    let files = generate(&schema).unwrap();
    let types = file(&files, "types.py");
    assert!(
        types.contains("Thing = TypedDict("),
        "keyword field must force the functional form: {types}"
    );
    assert!(types.contains("\"import\": str"), "{types}");

    let queries = file(&files, "queries.py");
    assert!(queries.contains("from_: str,"), "keyword param must be escaped: {queries}");
    assert!(
        queries.contains("variables = {\"from\": from_}"),
        "the wire key must stay the original GraphQL name: {queries}"
    );
    // The document itself uses the GraphQL name, untouched.
    assert!(queries.contains("$from: String!"), "{queries}");
}

/// #1033 — `CPython` applies private name mangling to identifiers in a class body,
/// so `class User(TypedDict): __typename: ...` declares the key
/// `_User__typename`. The wire dict has `__typename`, so any consumer that
/// introspects the `TypedDict` at runtime — `typeguard.check_type`,
/// `pydantic.TypeAdapter(...).validate_python`, anything driven by
/// `__annotations__` or `__required_keys__` — rejects a perfectly valid response
/// for a missing required key, and reports `__typename` as extra.
///
/// The escape hatch already existed (the functional `TypedDict("X", {...})` form,
/// where keys are plain strings) but fired only for Python keywords.
///
/// ⚠ Neither existing gate can see this: `ty` does not model mangling — it
/// accepts `u["__typename"]` and rejects `u["_User__typename"]` — and
/// `python3 -m compileall` only checks syntax. Only runtime introspection of the
/// emitted class shows it, which is why the consumer test now asserts on
/// `__required_keys__`.
#[test]
fn typename_is_declared_under_the_key_the_wire_actually_carries() {
    let types = file(&generate(&fixture()).unwrap(), "types.py");

    assert!(
        types.contains("User = TypedDict("),
        "a mangling field name must force the functional form: {types}"
    );
    assert!(
        types.contains("\"__typename\": Literal[\"User\"]"),
        "the discriminant must be a plain string key: {types}"
    );
}

/// #1034 — `doc_comment` collapsed only `'\n'`. Python source is read with
/// universal newlines, so a lone `\r` terminates a `#` comment and everything
/// after it becomes module-level code, executed on import.
///
/// Verified against `CPython`: a file containing `# desc\rINJECTED = 1` imports
/// with `INJECTED == 1`. The `TypeScript` twin has guarded its equivalent hole
/// (`*/`) with a dedicated test since it was written; the Python side had none,
/// while its own doc comment claimed author text "can never escape into code".
#[test]
fn a_carriage_return_in_a_description_cannot_escape_the_comment() {
    let mut schema = CompiledSchema::new();

    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.description = Some("first line\rINJECTED = 1".to_string());
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    schema.types.push(thing);

    let types = file(&generate(&schema).unwrap(), "types.py");

    assert!(
        !types.contains('\r'),
        "a carriage return must never reach the generated source: {types:?}"
    );
    assert!(
        types.contains("INJECTED = 1"),
        "the text itself is still carried, as comment prose: {types}"
    );
}

/// The second, likelier half of #1034: an ordinary CRLF description is not code
/// execution but a broken build. `\n` became a space, so `"one\r\ntwo"` emitted
/// `# one\r two` — whose continuation line starts with a space, giving
/// `IndentationError` on import while `generate-client` still printed its success
/// line and exited 0.
#[test]
fn a_crlf_description_does_not_break_the_generated_module() {
    let mut schema = CompiledSchema::new();

    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.description = Some("first line\r\nsecond line".to_string());
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    schema.types.push(thing);

    let types = file(&generate(&schema).unwrap(), "types.py");

    assert!(!types.contains('\r'), "CRLF must be collapsed like any newline: {types:?}");
    assert!(
        types.contains("# first line second line"),
        "both lines belong on the one comment line: {types}"
    );
}

/// #1035 — `emit_operation_fn` interpolated the `GraphQL` operation name straight
/// into `def {name}(`. `py_param_name`/`is_py_keyword` existed and were applied
/// to arguments and `TypedDict` fields, but never at the function-name site, so a
/// mutation named `import` emitted `def import(` — a `SyntaxError` that makes the
/// **entire** generated package unimportable, not just that operation.
///
/// The fix must be wire-neutral: the document and the response key keep the
/// original `GraphQL` name, exactly as the argument escaping already does.
#[test]
fn a_keyword_operation_name_is_escaped_without_changing_the_wire_shape() {
    let mut schema = CompiledSchema::new();

    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    schema.types.push(thing);

    schema.mutations.push(MutationDefinition::new("import", "Thing"));

    let mutations = file(&generate(&schema).unwrap(), "mutations.py");

    assert!(
        mutations.contains("def import_("),
        "a keyword operation name must be escaped: {mutations}"
    );
    assert!(
        mutations.contains("data[\"import\"]"),
        "the response key must stay the original GraphQL name: {mutations}"
    );
    assert!(
        mutations.contains("mutation import"),
        "the document must stay the original GraphQL name: {mutations}"
    );
}

/// Every pgvector field type renders as the surface it actually has (#959).
///
/// The wildcard arm in `field_type_py` exists to keep a future `#[non_exhaustive]`
/// scalar compiling, and that is exactly what let `HalfVector` and `SparseVector`
/// degrade to `Any` when they were added: the generator kept building, the generated
/// client kept passing `ty`, and a caller's embedding lost its type.
#[test]
fn every_vector_type_maps_to_its_own_surface() {
    // `[Float!]!` in GraphQL, whatever the column's precision.
    assert_eq!(field_type_py(&FieldType::Vector), "list[float]");
    assert_eq!(field_type_py(&FieldType::HalfVector), "list[float]");
    // Each of these is a string in its own text form: a run of 0/1 for a bit
    // vector, `{1:0.5,7:0.25}/1000` for a sparse one.
    assert_eq!(field_type_py(&FieldType::BitVector), "str");
    assert_eq!(field_type_py(&FieldType::SparseVector), "str");
}
