version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: benchmark_db
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../shared/database/seed-data-small.sql:/docker-entrypoint-initdb.d/02-seed.sql
    ports:
      - "5432:5432"

  postgraphile:
    image: graphile/postgraphile:4.14.0
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://benchmark:benchmark@postgres:5432/benchmark_db
    command:
      - --connection
      - postgres://benchmark:benchmark@postgres:5432/benchmark_db
      - --schema
      - public
      - --watch
      - --enhance-graphiql
      - --dynamic-json
      - --no-setof-functions-contain-nulls
      - --no-ignore-rbac
      - --show-error-stack=json
      - --extended-errors
      - hint,detail,errcode
      - --export-schema-json
      - schema.json
      - --graphiql
      - /graphiql
      - --port
      - "5000"
      - --host
      - "0.0.0.0"
