source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

group :development, :test do
  gem "rspec", "~> 3.12"
  gem "rspec-its", "~> 1.3"
  gem "rubocop", "~> 1.40"
  gem "rake", "~> 13.0"
end
