//! Rust client generator.
//!
//! `generate(&CompiledSchema)` returns a [`Generated`] map of Rust files forming
//! a module tree a consumer drops into their crate (`src/generated/` next to a
//! `pub mod generated;`). The `GraphQL` documents come from `client::common` and
//! are byte-identical to every other generator's; this module owns the Rust
//! packaging: which files exist, the header stamp, and the `mod.rs` re-exports.
//!
//! The generated code depends on `serde` (with `derive`) and `serde_json`, and
//! on nothing else: Rust has no HTTP client in `std`, so the transport is a
//! trait the consumer implements — see the `client` module's `Transport`.

mod emit;
mod render;
mod runtime;

use std::path::PathBuf;

use fraiseql_core::schema::CompiledSchema;

pub(super) use super::common::SchemaCtx as Ctx;
use crate::{Generated, Result};

/// Generate a Rust client from a compiled schema.
///
/// Returns a map of relative path → file content. Conditional files
/// (`enums.rs`, `inputs.rs`, `mutations.rs`, `relationships.rs`) are present
/// only when the schema has the corresponding definitions; `mod.rs` declares
/// exactly the files that were emitted.
///
/// # Errors
///
/// Returns an error if the schema cannot be hashed for stamping (see
/// [`crate::client::schema_hash`]).
pub fn generate(schema: &CompiledSchema) -> Result<Generated> {
    let ctx = Ctx::new(schema);
    let hash = super::schema_hash(schema)?;

    let mut files = Generated::new();
    let mut modules: Vec<&str> = Vec::new();
    let add = |files: &mut Generated,
               modules: &mut Vec<&'static str>,
               name: &'static str,
               body: String| {
        files.insert(PathBuf::from(format!("{name}.rs")), stamp(&body, &hash));
        modules.push(name);
    };

    add(&mut files, &mut modules, "client", runtime::CLIENT_RS.to_string());
    add(&mut files, &mut modules, "types", emit::types(&ctx));

    if !schema.enums.is_empty() {
        add(&mut files, &mut modules, "enums", emit::enums(schema));
    }
    if !schema.input_types.is_empty() {
        add(&mut files, &mut modules, "inputs", emit::inputs(&ctx));
    }
    if !schema.queries.is_empty() {
        add(&mut files, &mut modules, "queries", emit::queries(&ctx));
    }
    if !schema.mutations.is_empty() {
        add(&mut files, &mut modules, "mutations", emit::mutations(&ctx));
    }
    if ctx.has_relationships {
        add(&mut files, &mut modules, "relationships", emit::relationships(schema));
    }

    files.insert(PathBuf::from("mod.rs"), stamp(&emit::module(&modules), &hash));

    Ok(files)
}

/// Prepend the auto-generated header (with the schema hash) to a file body.
fn stamp(body: &str, hash: &str) -> String {
    format!(
        "// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n// schema-hash: {hash}\n// fraiseql-codegen: {version}\n\n{body}",
        version = env!("CARGO_PKG_VERSION"),
    )
}

#[cfg(test)]
mod tests;
