//! Tests for the Rust client generator.
//!
//! Structural assertions on the emitted files. The "does the output compile"
//! direction runs in CI (`sdk-conformance.yml` generates from the canonical
//! conformance fixture and runs `cargo check` with warnings denied) and in
//! `tests/client_rust_consumer.rs`.

#![allow(clippy::unwrap_used, clippy::panic)] // Reason: test code, panics are acceptable

use std::path::PathBuf;

use fraiseql_core::schema::{
    ArgumentDefinition, CompiledSchema, EnumDefinition, EnumValueDefinition, FieldDefinition,
    FieldType, InputFieldDefinition, InputObjectDefinition, MutationDefinition, QueryDefinition,
    TypeDefinition, UnionDefinition,
};

use super::{
    generate,
    render::{field_type_rs, pascal_case, rs_ident, snake_case},
};

fn fixture() -> CompiledSchema {
    let mut schema = CompiledSchema::new();

    let mut user = TypeDefinition::new("User", "v_user");
    user.fields.push(FieldDefinition::new("id", FieldType::Id));
    user.fields.push(FieldDefinition::new("email", FieldType::String));
    let mut display_name = FieldDefinition::new("displayName", FieldType::String);
    display_name.nullable = true;
    user.fields.push(display_name);
    user.fields
        .push(FieldDefinition::new("role", FieldType::Enum("UserRole".to_string())));
    schema.types.push(user);

    let mut not_found = TypeDefinition::new("NotFoundError", "");
    not_found.is_error = true;
    not_found.fields.push(FieldDefinition::new("message", FieldType::String));
    schema.types.push(not_found);

    schema.enums.push(EnumDefinition {
        name:        "UserRole".to_string(),
        values:      vec![
            EnumValueDefinition {
                name:        "ADMIN".to_string(),
                description: None,
                deprecation: None,
            },
            EnumValueDefinition {
                name:        "IN_REVIEW".to_string(),
                description: None,
                deprecation: None,
            },
        ],
        description: None,
    });

    schema
        .input_types
        .push(InputObjectDefinition::new("CreateUserInput").with_fields(vec![
            // Requiredness in the encoding the runtime enforces. A trailing `!`
            // on the type string is resolved into this flag at the compiler seam,
            // so a compiled schema never carries both (#1065).
            InputFieldDefinition::new("email", "String").with_nullable(false),
            InputFieldDefinition::new("role", "UserRole"),
        ]));

    let mut get_user = QueryDefinition::new("getUser", "User");
    get_user.nullable = true;
    get_user.arguments.push(ArgumentDefinition::new("id", FieldType::Id));
    schema.queries.push(get_user);

    let mut users = QueryDefinition::new("users", "User").returning_list();
    let mut limit = ArgumentDefinition::new("limit", FieldType::Int);
    limit.nullable = true;
    users.arguments.push(limit);
    schema.queries.push(users);

    let mut relay = QueryDefinition::new("usersConnection", "User");
    relay.relay = true;
    schema.queries.push(relay);

    let mut create = MutationDefinition::new("createUser", "User");
    create.arguments.push(ArgumentDefinition::new(
        "input",
        FieldType::Input("CreateUserInput".to_string()),
    ));
    schema.mutations.push(create);

    schema
}

fn file(files: &crate::Generated, name: &str) -> String {
    files
        .get(&PathBuf::from(name))
        .unwrap_or_else(|| panic!("missing generated file {name}"))
        .clone()
}

#[test]
fn emits_the_expected_files() {
    let files = generate(&fixture()).unwrap();
    for name in [
        "mod.rs",
        "client.rs",
        "types.rs",
        "enums.rs",
        "inputs.rs",
        "queries.rs",
        "mutations.rs",
    ] {
        assert!(files.contains_key(&PathBuf::from(name)), "missing {name}");
    }
    // No relationships in the fixture → no relationships.rs.
    assert!(!files.contains_key(&PathBuf::from("relationships.rs")));
}

#[test]
fn every_file_is_stamped_with_the_schema_hash() {
    let files = generate(&fixture()).unwrap();
    for (path, content) in &files {
        assert!(
            content.starts_with(
                "// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n// schema-hash: "
            ),
            "{} is missing the stamp",
            path.display()
        );
    }
}

/// `GraphQL` lets a query and a mutation share a name, so two glob re-exports
/// would hand the consumer an ambiguity at their own use site. Data types are
/// re-exported; operations stay behind `queries::` / `mutations::`.
#[test]
fn the_module_reexports_types_but_not_operations() {
    let module = file(&generate(&fixture()).unwrap(), "mod.rs");
    assert!(module.contains("pub mod queries;"), "{module}");
    assert!(module.contains("pub use types::*;"), "{module}");
    assert!(module.contains("pub use enums::*;"), "{module}");
    assert!(!module.contains("pub use queries::*;"), "{module}");
    assert!(!module.contains("pub use mutations::*;"), "{module}");
}

#[test]
fn objects_are_structs_with_renamed_fields() {
    let types = file(&generate(&fixture()).unwrap(), "types.rs");
    assert!(types.contains("pub struct User {"), "{types}");
    assert!(types.contains("pub id: String,"), "{types}");
    assert!(
        types.contains("#[serde(rename = \"displayName\")]\n    pub display_name: Option<String>,"),
        "snake_cased fields must keep their wire name: {types}"
    );
    assert!(types.contains("pub role: UserRole,"), "{types}");
    assert!(types.contains("use super::enums::UserRole;"), "{types}");
}

/// `serde`'s internally tagged representation strips `__typename` before the
/// variant sees the object, so a union member decoded through the union has no
/// `__typename` field at all — `default` is what keeps that from being an error,
/// and `skip_serializing` keeps the round trip from emitting the tag twice.
#[test]
fn typename_is_defaulted_and_never_re_serialized() {
    let types = file(&generate(&fixture()).unwrap(), "types.rs");
    assert!(
        types.contains("#[serde(rename = \"__typename\", default, skip_serializing)]"),
        "{types}"
    );
}

#[test]
fn error_type_carries_the_injected_status_field() {
    let types = file(&generate(&fixture()).unwrap(), "types.rs");
    let block = types.split("pub struct NotFoundError").nth(1).expect("NotFoundError emitted");
    assert!(
        block.contains("pub status: String,"),
        "error types must carry the runtime-injected status: {types}"
    );
}

#[test]
fn enums_are_renamed_unit_variants() {
    let enums = file(&generate(&fixture()).unwrap(), "enums.rs");
    assert!(enums.contains("pub enum UserRole {"), "{enums}");
    assert!(enums.contains("#[serde(rename = \"ADMIN\")]\n    Admin,"), "{enums}");
    assert!(enums.contains("#[serde(rename = \"IN_REVIEW\")]\n    InReview,"), "{enums}");
}

#[test]
fn optional_input_fields_are_skipped_when_none() {
    let inputs = file(&generate(&fixture()).unwrap(), "inputs.rs");
    assert!(inputs.contains("pub email: String,"), "{inputs}");
    assert!(
        inputs.contains(
            "#[serde(default, skip_serializing_if = \"Option::is_none\")]\n    pub role: Option<UserRole>,"
        ),
        "{inputs}"
    );
}

#[test]
fn required_args_are_inserted_and_optional_ones_omitted() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.rs");
    assert!(queries.contains("pub fn get_user<T: Transport>("), "{queries}");
    assert!(
        queries.contains("    id: String,\n) -> Result<Option<User>, Error> {"),
        "{queries}"
    );
    assert!(queries.contains("var(&mut variables, \"id\", &id)?;"), "{queries}");
    assert!(queries.contains("    limit: Option<i32>,"), "{queries}");
    assert!(
        queries.contains("var_opt(&mut variables, \"limit\", limit.as_ref())?;"),
        "{queries}"
    );
}

/// An unused import is a warning, and the compile gate denies warnings — so the
/// runtime `use` line names only the helpers a file's operations actually call.
#[test]
fn runtime_imports_name_only_what_is_used() {
    let mut schema = CompiledSchema::new();
    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    schema.types.push(thing);
    // One query, no arguments at all: neither `var` nor `var_opt` is called.
    schema.queries.push(QueryDefinition::new("things", "Thing").returning_list());

    let queries = file(&generate(&schema).unwrap(), "queries.rs");
    assert!(
        queries.contains("use super::client::{Error, FraiseqlClient, Transport};"),
        "{queries}"
    );
    assert!(!queries.contains("var"), "{queries}");
    assert!(
        queries.contains("client.request(THINGS, serde_json::Map::new(), \"things\")"),
        "{queries}"
    );
}

#[test]
fn relay_queries_paginate_and_return_a_connection() {
    let files = generate(&fixture()).unwrap();
    let queries = file(&files, "queries.rs");
    assert!(queries.contains("pub fn users_connection<T: Transport>("), "{queries}");
    assert!(queries.contains("    first: Option<i32>,"), "{queries}");
    assert!(queries.contains("    after: Option<String>,"), "{queries}");
    assert!(queries.contains(") -> Result<Connection<User>, Error> {"), "{queries}");
    let types = file(&files, "types.rs");
    assert!(types.contains("pub struct Connection<T> {"), "{types}");
}

#[test]
fn mutations_expose_the_error_guard() {
    let mutations = file(&generate(&fixture()).unwrap(), "mutations.rs");
    assert!(
        mutations.contains("pub const ERROR_TYPENAMES: &[&str] = &[\"NotFoundError\"];"),
        "{mutations}"
    );
    assert!(
        mutations.contains("pub fn is_error_typename(typename: &str) -> bool"),
        "{mutations}"
    );
    assert!(mutations.contains("pub fn create_user<T: Transport>("), "{mutations}");
}

/// A `GraphQL` name that snake-cases onto a Rust keyword must not produce a
/// syntax error — while the wire name stays the original.
#[test]
fn rust_keywords_are_escaped_without_changing_the_wire_shape() {
    let mut schema = CompiledSchema::new();
    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    thing.fields.push(FieldDefinition::new("type", FieldType::String));
    schema.types.push(thing);
    let mut q = QueryDefinition::new("things", "Thing").returning_list();
    q.arguments.push(ArgumentDefinition::new("move", FieldType::String));
    schema.queries.push(q);

    let files = generate(&schema).unwrap();
    let types = file(&files, "types.rs");
    assert!(
        types.contains("#[serde(rename = \"type\")]\n    pub type_: String,"),
        "keyword field must be escaped and renamed: {types}"
    );

    let queries = file(&files, "queries.rs");
    assert!(
        queries.contains("    move_: String,"),
        "keyword param must be escaped: {queries}"
    );
    assert!(
        queries.contains("var(&mut variables, \"move\", &move_)?;"),
        "the wire key must stay the original GraphQL name: {queries}"
    );
    assert!(queries.contains("$move: String!"), "{queries}");
}

/// A union is the one place Rust's type system maps onto `GraphQL`'s exactly:
/// an internally tagged enum discriminated by `__typename`.
#[test]
fn unions_are_internally_tagged_enums() {
    let mut schema = fixture();
    schema.unions.push(UnionDefinition {
        name:         "CreateUserResult".to_string(),
        description:  None,
        member_types: vec!["User".to_string(), "NotFoundError".to_string()],
    });
    let types = file(&generate(&schema).unwrap(), "types.rs");
    assert!(types.contains("#[serde(tag = \"__typename\")]"), "{types}");
    assert!(types.contains("pub enum CreateUserResult {"), "{types}");
    assert!(types.contains("    User(User),"), "{types}");
    assert!(types.contains("    NotFoundError(NotFoundError),"), "{types}");
}

/// A union with no members cannot be an enum — an uninhabited type would make
/// every response undecodable. It degrades to the untyped value, as the Python
/// generator's `Any` does.
#[test]
fn empty_unions_degrade_to_a_json_value() {
    let mut schema = fixture();
    schema.unions.push(UnionDefinition {
        name:         "Nothing".to_string(),
        description:  None,
        member_types: Vec::new(),
    });
    let types = file(&generate(&schema).unwrap(), "types.rs");
    assert!(types.contains("pub type Nothing = serde_json::Value;"), "{types}");
}

/// Every pgvector field type renders as the surface it actually has (#959).
///
/// `FieldType` is `#[non_exhaustive]` and defined in another crate, so
/// `field_type_rs` must end in a wildcard arm — which is exactly what let
/// `HalfVector` and `SparseVector` degrade to `Any`/`unknown` in the two older
/// generators when they were added. This test is the only thing standing
/// between a newly added variant and a silent `serde_json::Value`.
#[test]
fn every_field_type_maps_to_its_own_surface() {
    for (ft, expected) in [
        (FieldType::String, "String"),
        (FieldType::Id, "String"),
        (FieldType::Uuid, "String"),
        (FieldType::Decimal, "String"),
        (FieldType::DateTime, "String"),
        (FieldType::Date, "String"),
        (FieldType::Time, "String"),
        (FieldType::Scalar("Email".to_string()), "String"),
        (FieldType::Int, "i32"),
        (FieldType::Float, "f64"),
        (FieldType::Boolean, "bool"),
        (FieldType::Json, "serde_json::Value"),
        // `[Float!]!` in GraphQL, whatever the column's precision.
        (FieldType::Vector, "Vec<f64>"),
        (FieldType::HalfVector, "Vec<f64>"),
        // Each of these is a string in its own text form: a run of 0/1 for a bit
        // vector, `{1:0.5,7:0.25}/1000` for a sparse one.
        (FieldType::BitVector, "String"),
        (FieldType::SparseVector, "String"),
        (FieldType::List(Box::new(FieldType::String)), "Vec<String>"),
        (FieldType::Object("User".to_string()), "User"),
        (FieldType::Enum("UserRole".to_string()), "UserRole"),
        (FieldType::Input("UserFilter".to_string()), "UserFilter"),
        (FieldType::Interface("Node".to_string()), "Node"),
        (FieldType::Union("Result".to_string()), "Result"),
    ] {
        assert_eq!(field_type_rs(&ft), expected, "{ft:?}");
    }
}

#[test]
fn casing_helpers_follow_rust_conventions() {
    assert_eq!(snake_case("displayName"), "display_name");
    assert_eq!(snake_case("postsConnection"), "posts_connection");
    assert_eq!(snake_case("userIDValue"), "user_id_value");
    assert_eq!(snake_case("id"), "id");
    assert_eq!(rs_ident("type"), "type_");
    assert_eq!(pascal_case("IN_PROGRESS"), "InProgress");
    assert_eq!(pascal_case("ADMIN"), "Admin");
    // `SELF` pascal-cases onto the reserved `Self`.
    assert_eq!(pascal_case("SELF"), "Self_");
}

/// A GraphQL input object may reference itself — the derived filter surface puts
/// `_not: OrderWhereInput` on every entity filter (#1154). A Rust struct that
/// holds itself **by value** is infinitely sized, and the generated crate fails
/// to compile with `E0072`, which is what reached CI.
///
/// A `Vec<T>` field is already an indirection, so `_and`/`_or` need no box; only
/// the bare reference does.
#[test]
fn a_self_referential_input_field_is_boxed_but_a_list_of_them_is_not() {
    let mut schema = CompiledSchema::new();
    schema.input_types.push(
        InputObjectDefinition::new("OrderWhereInput")
            .with_field(InputFieldDefinition::new("reference", "StringFilter"))
            .with_field(InputFieldDefinition::new("_and", "[OrderWhereInput!]"))
            .with_field(InputFieldDefinition::new("_not", "OrderWhereInput")),
    );
    schema.input_types.push(
        InputObjectDefinition::new("StringFilter")
            .with_field(InputFieldDefinition::new("eq", "String")),
    );

    let files = generate(&schema).expect("generation succeeds");
    let inputs = files
        .iter()
        .find(|(p, _)| p.ends_with("inputs.rs"))
        .map(|(_, body)| body.clone())
        .expect("inputs.rs is emitted");

    assert!(
        inputs.contains("Option<Box<OrderWhereInput>>"),
        "the self-reference must be boxed or the struct is infinitely sized:\n{inputs}"
    );
    assert!(
        inputs.contains("Option<Vec<OrderWhereInput>>"),
        "a list is already an indirection and must not be boxed:\n{inputs}"
    );
    // A field that cannot reach back to its container stays unboxed — boxing
    // everything would be correct but needlessly awkward to use.
    assert!(
        inputs.contains("Option<StringFilter>"),
        "a non-cyclic input reference must stay unboxed:\n{inputs}"
    );
}

/// Mutual recursion closes the same cycle one hop further out, which a
/// self-reference check alone would miss.
#[test]
fn a_mutually_recursive_input_pair_is_boxed_on_both_sides() {
    let mut schema = CompiledSchema::new();
    schema.input_types.push(
        InputObjectDefinition::new("OrderWhereInput")
            .with_field(InputFieldDefinition::new("customer", "CustomerWhereInput")),
    );
    schema.input_types.push(
        InputObjectDefinition::new("CustomerWhereInput")
            .with_field(InputFieldDefinition::new("primaryOrder", "OrderWhereInput")),
    );

    let files = generate(&schema).expect("generation succeeds");
    let inputs = files
        .iter()
        .find(|(p, _)| p.ends_with("inputs.rs"))
        .map(|(_, body)| body.clone())
        .expect("inputs.rs is emitted");

    assert!(inputs.contains("Option<Box<CustomerWhereInput>>"), "got:\n{inputs}");
    assert!(inputs.contains("Option<Box<OrderWhereInput>>"), "got:\n{inputs}");
}
