//! Go client generator.
//!
//! `generate(&CompiledSchema)` returns a [`Generated`] map of Go files
//! implementing a typed, standard-library-only client for **Go ≥ 1.21** (the
//! Relay `Connection[T]` needs generics). The `GraphQL` documents come from
//! `client::common` and are byte-identical to every other generator's; this
//! module owns the Go packaging: which files exist, the header stamp, and the
//! `package` clause.
//!
//! Unlike the `TypeScript` and Python clients, every file lands in one package,
//! so nothing needs cross-file imports and there is no index/`__init__` to
//! re-export.

mod emit;
mod render;
mod runtime;

use std::path::PathBuf;

use fraiseql_core::schema::CompiledSchema;

pub(super) use super::common::SchemaCtx as Ctx;
use crate::{Generated, Result};

/// The package every generated file declares.
const PACKAGE: &str = "fraiseqlclient";

/// Generate a Go client from a compiled schema.
///
/// Returns a map of relative path → file content. Conditional files
/// (`enums.go`, `inputs.go`, `mutations.go`, `relationships.go`) are present
/// only when the schema has the corresponding definitions.
///
/// # Errors
///
/// Returns an error if the schema cannot be hashed for stamping (see
/// [`crate::client::schema_hash`]).
pub fn generate(schema: &CompiledSchema) -> Result<Generated> {
    let ctx = Ctx::new(schema);
    let hash = super::schema_hash(schema)?;

    let mut files = Generated::new();
    let mut add = |name: &str, body: String| {
        files.insert(PathBuf::from(format!("{name}.go")), stamp(&body, &hash));
    };

    add("client", runtime::CLIENT_GO.to_string());
    add("types", emit::types(&ctx));

    if !schema.enums.is_empty() {
        add("enums", emit::enums(schema));
    }
    if !schema.input_types.is_empty() {
        add("inputs", emit::inputs(schema));
    }
    if !schema.queries.is_empty() {
        add("queries", emit::queries(&ctx));
    }
    if !schema.mutations.is_empty() {
        add("mutations", emit::mutations(&ctx));
    }
    if ctx.has_relationships {
        add("relationships", emit::relationships(schema));
    }

    Ok(files)
}

/// Prepend the auto-generated header (with the schema hash) and the `package`
/// clause to a file body.
///
/// The blank line between the header and `package` is load-bearing: a comment
/// block touching the clause would become the package doc comment, and every
/// file would then claim to document the package.
fn stamp(body: &str, hash: &str) -> String {
    format!(
        "// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n// schema-hash: {hash}\n// fraiseql-codegen: {version}\n\npackage {PACKAGE}\n\n{body}",
        version = env!("CARGO_PKG_VERSION"),
    )
}

#[cfg(test)]
mod tests;
