//! Tests for the Go client generator.
//!
//! Structural assertions on the emitted files. The "does the output compile"
//! direction runs in CI (`sdk-conformance.yml` generates from the canonical
//! conformance fixture and runs `gofmt -l`, `go vet` and `go build` on the
//! output) and in `tests/client_go_consumer.rs`.

#![allow(clippy::unwrap_used, clippy::panic)] // Reason: test code, panics are acceptable

use std::path::PathBuf;

use fraiseql_core::schema::{
    ArgumentDefinition, CompiledSchema, EnumDefinition, EnumValueDefinition, FieldDefinition,
    FieldType, InputFieldDefinition, InputObjectDefinition, MutationDefinition, QueryDefinition,
    TypeDefinition, UnionDefinition,
};

use super::{
    generate,
    render::{field_type_go, field_type_go_nullable, go_enum_suffix, go_export},
};

fn fixture() -> CompiledSchema {
    let mut schema = CompiledSchema::new();

    let mut user = TypeDefinition::new("User", "v_user");
    user.fields.push(FieldDefinition::new("id", FieldType::Id));
    user.fields.push(FieldDefinition::new("email", FieldType::String));
    let mut age = FieldDefinition::new("age", FieldType::Int);
    age.nullable = true;
    user.fields.push(age);
    user.fields
        .push(FieldDefinition::new("role", FieldType::Enum("UserRole".to_string())));
    schema.types.push(user);

    let mut not_found = TypeDefinition::new("NotFoundError", "");
    not_found.is_error = true;
    not_found.fields.push(FieldDefinition::new("message", FieldType::String));
    schema.types.push(not_found);

    schema.enums.push(EnumDefinition {
        name:        "UserRole".to_string(),
        values:      vec![
            EnumValueDefinition {
                name:        "ADMIN".to_string(),
                description: None,
                deprecation: None,
            },
            EnumValueDefinition {
                name:        "MEMBER".to_string(),
                description: None,
                deprecation: None,
            },
        ],
        description: None,
    });

    schema
        .input_types
        .push(InputObjectDefinition::new("CreateUserInput").with_fields(vec![
            InputFieldDefinition::new("email", "String!"),
            InputFieldDefinition::new("role", "UserRole"),
        ]));

    let mut get_user = QueryDefinition::new("getUser", "User");
    get_user.nullable = true;
    get_user.arguments.push(ArgumentDefinition::new("id", FieldType::Id));
    schema.queries.push(get_user);

    let mut users = QueryDefinition::new("users", "User").returning_list();
    let mut limit = ArgumentDefinition::new("limit", FieldType::Int);
    limit.nullable = true;
    users.arguments.push(limit);
    schema.queries.push(users);

    let mut relay = QueryDefinition::new("usersConnection", "User");
    relay.relay = true;
    schema.queries.push(relay);

    let mut create = MutationDefinition::new("createUser", "User");
    create.arguments.push(ArgumentDefinition::new(
        "input",
        FieldType::Input("CreateUserInput".to_string()),
    ));
    schema.mutations.push(create);

    schema
}

fn file(files: &crate::Generated, name: &str) -> String {
    files
        .get(&PathBuf::from(name))
        .unwrap_or_else(|| panic!("missing generated file {name}"))
        .clone()
}

#[test]
fn emits_the_expected_files() {
    let files = generate(&fixture()).unwrap();
    for name in [
        "client.go",
        "types.go",
        "enums.go",
        "inputs.go",
        "queries.go",
        "mutations.go",
    ] {
        assert!(files.contains_key(&PathBuf::from(name)), "missing {name}");
    }
    // No relationships in the fixture → no relationships.go.
    assert!(!files.contains_key(&PathBuf::from("relationships.go")));
}

#[test]
fn every_file_is_stamped_and_declares_the_package() {
    let files = generate(&fixture()).unwrap();
    for (path, content) in &files {
        assert!(
            content.starts_with(
                "// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n// schema-hash: "
            ),
            "{} is missing the stamp",
            path.display()
        );
        assert!(
            content.contains("\n\npackage fraiseqlclient\n"),
            "{} must declare the package after a blank line",
            path.display()
        );
    }
}

#[test]
fn objects_are_structs_with_json_tags() {
    let types = file(&generate(&fixture()).unwrap(), "types.go");
    assert!(types.contains("type User struct {"), "{types}");
    assert!(types.contains("Typename string   `json:\"__typename\"`"), "{types}");
    assert!(types.contains("Email    string   `json:\"email\"`"), "{types}");
    assert!(
        types.contains("Age      *int     `json:\"age\"`"),
        "nullable → pointer: {types}"
    );
    assert!(types.contains("Role     UserRole `json:\"role\"`"), "{types}");
}

#[test]
fn error_type_carries_the_injected_status_field() {
    let types = file(&generate(&fixture()).unwrap(), "types.go");
    let block = types.split("type NotFoundError struct").nth(1).expect("NotFoundError emitted");
    assert!(
        block.contains("Status  string `json:\"status\"`"),
        "error types must carry the runtime-injected status: {types}"
    );
}

#[test]
fn enums_are_string_types_with_constants() {
    let enums = file(&generate(&fixture()).unwrap(), "enums.go");
    assert!(enums.contains("type UserRole string"), "{enums}");
    assert!(enums.contains("UserRoleAdmin  UserRole = \"ADMIN\""), "{enums}");
    assert!(enums.contains("UserRoleMember UserRole = \"MEMBER\""), "{enums}");
}

#[test]
fn optional_input_fields_are_pointers_with_omitempty() {
    let inputs = file(&generate(&fixture()).unwrap(), "inputs.go");
    assert!(inputs.contains("Email string    `json:\"email\"`"), "{inputs}");
    assert!(inputs.contains("Role  *UserRole `json:\"role,omitempty\"`"), "{inputs}");
}

#[test]
fn required_args_build_a_literal_variables_map() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.go");
    assert!(
        queries.contains("func (c *Client) GetUser(id string) (*User, error) {"),
        "{queries}"
    );
    assert!(
        queries.contains("variables := map[string]any{\n\t\t\"id\": id,\n\t}"),
        "required-only args must be a literal map: {queries}"
    );
    assert!(queries.contains("Result *User `json:\"getUser\"`"), "{queries}");
}

/// A typed nil inside an `any` is not `== nil`, so an optional argument must be
/// omitted by testing the *typed* parameter before boxing it into the map.
/// Filtering after the fact would send `"limit": null` for every unset argument.
#[test]
fn optional_args_are_omitted_before_boxing() {
    let queries = file(&generate(&fixture()).unwrap(), "queries.go");
    assert!(
        queries.contains("func (c *Client) Users(limit *int) ([]User, error) {"),
        "{queries}"
    );
    assert!(
        queries.contains("if limit != nil {\n\t\tvariables[\"limit\"] = limit\n\t}"),
        "optional args must be nil-checked at their typed parameter: {queries}"
    );
    assert!(!queries.contains("omitNil"), "no post-hoc filtering: {queries}");
}

#[test]
fn relay_queries_paginate_and_return_a_connection() {
    let files = generate(&fixture()).unwrap();
    let queries = file(&files, "queries.go");
    assert!(
        queries.contains(
            "func (c *Client) UsersConnection(first *int, after *string) (Connection[User], error) {"
        ),
        "{queries}"
    );
    let types = file(&files, "types.go");
    assert!(types.contains("type Connection[T any] struct {"), "{types}");
    assert!(types.contains("type Edge[T any] struct {"), "{types}");
}

#[test]
fn mutations_expose_the_error_guard() {
    let mutations = file(&generate(&fixture()).unwrap(), "mutations.go");
    assert!(mutations.contains("var ErrorTypenames = map[string]bool{"), "{mutations}");
    assert!(mutations.contains("\"NotFoundError\": true,"), "{mutations}");
    assert!(mutations.contains("func IsErrorResult(typename string) bool"), "{mutations}");
    assert!(
        mutations.contains("func (c *Client) CreateUser(input CreateUserInput)"),
        "{mutations}"
    );
}

/// Go's keywords are all lowercase, so they can only collide with the
/// *unexported* identifiers — parameters — never with an exported field name.
/// A field whose `GraphQL` name does not start with a letter would map to an
/// unexported Go field, which `encoding/json` ignores **silently**; those are
/// prefixed instead.
#[test]
fn identifiers_stay_exported_and_keyword_safe() {
    let mut schema = CompiledSchema::new();
    let mut thing = TypeDefinition::new("Thing", "v_thing");
    thing.fields.push(FieldDefinition::new("id", FieldType::Id));
    thing.fields.push(FieldDefinition::new("_internal", FieldType::String));
    schema.types.push(thing);
    let mut q = QueryDefinition::new("things", "Thing").returning_list();
    q.arguments.push(ArgumentDefinition::new("type", FieldType::String));
    schema.queries.push(q);

    let files = generate(&schema).unwrap();
    let types = file(&files, "types.go");
    assert!(
        types.contains("X_internal string `json:\"_internal\"`"),
        "a non-letter-initial field must still be exported: {types}"
    );

    let queries = file(&files, "queries.go");
    assert!(queries.contains("type_ string"), "keyword param must be escaped: {queries}");
    assert!(
        queries.contains("\"type\": type_,"),
        "the wire key must stay the original GraphQL name: {queries}"
    );
    assert!(queries.contains("$type: String!"), "{queries}");
}

/// A union decodes into the member its `__typename` names; Go has no sum type,
/// so the discriminant is checked in a generated `UnmarshalJSON`.
#[test]
fn unions_decode_by_typename() {
    let mut schema = fixture();
    schema.unions.push(UnionDefinition {
        name:         "CreateUserResult".to_string(),
        description:  None,
        member_types: vec!["User".to_string(), "NotFoundError".to_string()],
    });
    let types = file(&generate(&schema).unwrap(), "types.go");

    assert!(types.contains("type CreateUserResult struct {"), "{types}");
    assert!(types.contains("User          *User          `json:\"-\"`"), "{types}");
    assert!(
        types.contains("func (u *CreateUserResult) UnmarshalJSON(data []byte) error {"),
        "{types}"
    );
    assert!(types.contains("\tcase \"User\":"), "{types}");
    assert!(
        types.contains("return fmt.Errorf(\"unknown __typename %q for union CreateUserResult\""),
        "an unlisted member is an error, not a silent zero value: {types}"
    );
    assert!(types.contains("import (\n\t\"encoding/json\"\n\t\"fmt\"\n)"), "{types}");
}

/// A schema with no decodable union must not emit an import block — an unused
/// import is a **compile error** in Go, so the block is conditional.
#[test]
fn types_file_has_no_imports_without_a_union() {
    let types = file(&generate(&fixture()).unwrap(), "types.go");
    assert!(!types.contains("import ("), "{types}");
}

/// Every pgvector field type renders as the surface it actually has (#959).
///
/// `FieldType` is `#[non_exhaustive]` and defined in another crate, so
/// `field_type_go` must end in a wildcard arm — which is exactly what let
/// `HalfVector` and `SparseVector` degrade to `Any`/`unknown` in the two older
/// generators when they were added. This test is the only thing standing
/// between a newly added variant and a silent `any`.
#[test]
fn every_field_type_maps_to_its_own_surface() {
    for (ft, expected) in [
        (FieldType::String, "string"),
        (FieldType::Id, "string"),
        (FieldType::Uuid, "string"),
        (FieldType::Decimal, "string"),
        (FieldType::DateTime, "string"),
        (FieldType::Date, "string"),
        (FieldType::Time, "string"),
        (FieldType::Scalar("Email".to_string()), "string"),
        (FieldType::Int, "int"),
        (FieldType::Float, "float64"),
        (FieldType::Boolean, "bool"),
        (FieldType::Json, "any"),
        // `[Float!]!` in GraphQL, whatever the column's precision.
        (FieldType::Vector, "[]float64"),
        (FieldType::HalfVector, "[]float64"),
        // Each of these is a string in its own text form: a run of 0/1 for a bit
        // vector, `{1:0.5,7:0.25}/1000` for a sparse one.
        (FieldType::BitVector, "string"),
        (FieldType::SparseVector, "string"),
        (FieldType::List(Box::new(FieldType::String)), "[]string"),
        (FieldType::Object("User".to_string()), "User"),
        (FieldType::Enum("UserRole".to_string()), "UserRole"),
        (FieldType::Input("UserFilter".to_string()), "UserFilter"),
        (FieldType::Interface("Node".to_string()), "Node"),
        (FieldType::Union("Result".to_string()), "Result"),
    ] {
        assert_eq!(field_type_go(&ft), expected, "{ft:?}");
    }
}

/// Slices, maps and `any` already carry `nil`; wrapping them in a pointer would
/// add a second level of absence that no caller wants and JSON cannot express.
#[test]
fn nullability_only_adds_a_pointer_where_go_needs_one() {
    assert_eq!(field_type_go_nullable(&FieldType::Int, true), "*int");
    assert_eq!(field_type_go_nullable(&FieldType::Int, false), "int");
    assert_eq!(field_type_go_nullable(&FieldType::Vector, true), "[]float64");
    assert_eq!(field_type_go_nullable(&FieldType::Json, true), "any");
    assert_eq!(
        field_type_go_nullable(&FieldType::List(Box::new(FieldType::String)), true),
        "[]string"
    );
}

#[test]
fn enum_constants_and_exports_are_pascal_case() {
    assert_eq!(go_enum_suffix("ADMIN"), "Admin");
    assert_eq!(go_enum_suffix("IN_PROGRESS"), "InProgress");
    assert_eq!(go_export("displayName"), "DisplayName");
    assert_eq!(go_export("id"), "Id");
    assert_eq!(go_export("_internal"), "X_internal");
}

/// Operations are methods on `*Client` because Go has one exported namespace per
/// package and the canonical `GraphQL` schema collides inside it: a `user` query
/// and a `User` type would be two declarations of the same identifier.
///
/// This is not hypothetical — the canonical conformance fixture has exactly that
/// pair, and as package functions the generated client did not compile.
#[test]
fn an_operation_named_after_a_type_does_not_redeclare_it() {
    let mut schema = CompiledSchema::new();
    let mut user = TypeDefinition::new("User", "v_user");
    user.fields.push(FieldDefinition::new("id", FieldType::Id));
    schema.types.push(user);
    let mut query = QueryDefinition::new("user", "User");
    query.nullable = true;
    query.arguments.push(ArgumentDefinition::new("id", FieldType::Id));
    schema.queries.push(query);

    let files = generate(&schema).unwrap();
    let types = file(&files, "types.go");
    let queries = file(&files, "queries.go");

    assert!(types.contains("type User struct {"), "{types}");
    assert!(
        queries.contains("func (c *Client) User(id string) (*User, error) {"),
        "the operation must be a method, not a package-level `func User`: {queries}"
    );
    assert!(!queries.contains("func User("), "{queries}");
}
