spring:
  application:
    name: fraiseql-java-benchmark

  datasource:
    url: jdbc:postgresql://localhost:5432/fraiseql_benchmark
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 16
    show-sql: false

  graphql:
    graphiql:
      enabled: true
    path: /graphql

server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 20

logging:
  level:
    root: INFO
    com.fraiseql: DEBUG
    org.springframework.graphql: DEBUG
    org.hibernate.SQL: WARN
