supergraph:
  listen: 0.0.0.0:4000
  path: /graphql
  introspection: true

health_check:
  enabled: true
  listen: 0.0.0.0:8088
  path: /health

cors:
  allow_any_origin: true

traffic_shaping:
  router:
    timeout: 30s
