//! `TypeScript` client generator.
//!
//! `generate(&CompiledSchema)` returns a [`Generated`] map of `TypeScript` files
//! implementing a typed, `fetch`-based client. See `DESIGN-CLIENT-TS.md` for the
//! full specification; this module owns orchestration and the schema-walking
//! helpers, while [`emit`] owns the per-file rendering.

mod emit;
mod render;
mod runtime;

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use fraiseql_core::schema::{
    CompiledSchema, FieldDefinition, FieldType, InterfaceDefinition, TypeDefinition,
    UnionDefinition,
};

use crate::{Generated, Result};

/// Generate a `TypeScript` client from a compiled schema.
///
/// Returns a map of relative path → file content. Conditional files (`enums.ts`,
/// `inputs.ts`, `mutations.ts`, `relationships.ts`) are present only when the
/// schema has the corresponding definitions; `index.ts` re-exports exactly the
/// files that were emitted.
///
/// # Errors
///
/// Returns an error if the schema cannot be hashed for stamping (see
/// [`crate::client::schema_hash`]).
pub fn generate(schema: &CompiledSchema) -> Result<Generated> {
    let ctx = Ctx::new(schema);
    let hash = super::schema_hash(schema)?;

    let mut files = Generated::new();
    let mut modules: Vec<&str> = Vec::new();
    let add = |files: &mut Generated, modules: &mut Vec<&'static str>, name: &'static str, body: String| {
        files.insert(PathBuf::from(format!("{name}.ts")), stamp(&body, &hash));
        modules.push(name);
    };

    add(&mut files, &mut modules, "types", emit::types(&ctx));

    if !schema.enums.is_empty() {
        add(&mut files, &mut modules, "enums", emit::enums(schema));
    }
    if !schema.input_types.is_empty() {
        add(&mut files, &mut modules, "inputs", emit::inputs(&ctx));
    }
    if !schema.queries.is_empty() {
        add(&mut files, &mut modules, "queries", emit::queries(&ctx));
    }
    if !schema.mutations.is_empty() {
        add(&mut files, &mut modules, "mutations", emit::mutations(&ctx));
    }
    if ctx.has_relationships {
        add(&mut files, &mut modules, "relationships", emit::relationships(schema));
    }

    add(&mut files, &mut modules, "client", runtime::CLIENT_TS.to_string());

    files.insert(PathBuf::from("index.ts"), stamp(&emit::index(&modules), &hash));

    Ok(files)
}

/// Prepend the auto-generated header (with the schema hash) to a file body.
fn stamp(body: &str, hash: &str) -> String {
    format!(
        "// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n// schema-hash: {hash}\n// fraiseql-codegen: {version}\n\n{body}",
        version = env!("CARGO_PKG_VERSION"),
    )
}

/// Resolved lookups over a [`CompiledSchema`], shared by the emitters.
pub(super) struct Ctx<'a> {
    schema:           &'a CompiledSchema,
    object_types:     BTreeMap<&'a str, &'a TypeDefinition>,
    interfaces:       BTreeMap<&'a str, &'a InterfaceDefinition>,
    unions:           BTreeMap<&'a str, &'a UnionDefinition>,
    enum_names:       BTreeSet<&'a str>,
    input_names:      BTreeSet<&'a str>,
    error_typenames:  BTreeSet<&'a str>,
    has_relay:        bool,
    has_relationships: bool,
}

impl<'a> Ctx<'a> {
    fn new(schema: &'a CompiledSchema) -> Self {
        let object_types = schema.types.iter().map(|t| (t.name.as_str(), t)).collect();
        let interfaces = schema.interfaces.iter().map(|i| (i.name.as_str(), i)).collect();
        let unions = schema.unions.iter().map(|u| (u.name.as_str(), u)).collect();
        let enum_names = schema.enums.iter().map(|e| e.name.as_str()).collect();
        let input_names = schema.input_types.iter().map(|i| i.name.as_str()).collect();
        let error_typenames =
            schema.types.iter().filter(|t| t.is_error).map(|t| t.name.as_str()).collect();
        let has_relay = schema.queries.iter().any(|q| q.relay);
        let has_relationships = schema.types.iter().any(|t| !t.relationships.is_empty());

        Self {
            schema,
            object_types,
            interfaces,
            unions,
            enum_names,
            input_names,
            error_typenames,
            has_relay,
            has_relationships,
        }
    }

    /// Which generated module defines a referenced type name, if any.
    fn module_of(&self, name: &str) -> Option<&'static str> {
        if self.enum_names.contains(name) {
            Some("enums")
        } else if self.input_names.contains(name) {
            Some("inputs")
        } else if matches!(name, "Connection" | "Edge" | "PageInfo")
            || self.object_types.contains_key(name)
            || self.unions.contains_key(name)
            || self.interfaces.contains_key(name)
        {
            Some("types")
        } else {
            None
        }
    }
}

/// Leaf fields of a type, in declaration order (those the default document fetches).
fn leaf_fields(fields: &[FieldDefinition]) -> Vec<&FieldDefinition> {
    fields.iter().filter(|f| render::is_leaf(&f.field_type)).collect()
}

/// The innermost named type a [`FieldType`] references (recursing into lists).
fn referenced_named_type(ft: &FieldType) -> Option<&str> {
    match ft {
        FieldType::Enum(n)
        | FieldType::Object(n)
        | FieldType::Input(n)
        | FieldType::Interface(n)
        | FieldType::Union(n) => Some(n),
        FieldType::List(inner) => referenced_named_type(inner),
        _ => None,
    }
}

/// The base named type of an input-field `GraphQL` type **string** (strips `[]!`).
fn input_base_name(type_str: &str) -> String {
    type_str.chars().filter(|c| !matches!(c, '[' | ']' | '!' | ' ')).collect()
}

/// Render a sorted `import { ... } from "./module";` block for the given names,
/// grouped by the module that defines each name. Names not defined in any
/// generated module (scalars) are dropped.
fn render_imports(ctx: &Ctx, names: &BTreeSet<&str>, current: &str) -> String {
    let mut by_module: BTreeMap<&'static str, BTreeSet<&str>> = BTreeMap::new();
    for &name in names {
        if let Some(module) = ctx.module_of(name) {
            if module != current {
                by_module.entry(module).or_default().insert(name);
            }
        }
    }

    let mut out = String::new();
    for (module, idents) in by_module {
        let joined = idents.into_iter().collect::<Vec<_>>().join(", ");
        let _ = writeln!(out, "import type {{ {joined} }} from \"./{module}\";");
    }
    out
}
