//! `TypeScript` client generator.
//!
//! `generate(&CompiledSchema)` returns a [`Generated`] map of `TypeScript` files
//! implementing a typed, `fetch`-based client. See `DESIGN-CLIENT-TS.md` for the
//! full specification; this module owns orchestration and the schema-walking
//! helpers, while `emit` owns the per-file rendering.

mod emit;
mod functions_dts;
mod render;
mod runtime;

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    path::PathBuf,
};

use fraiseql_core::schema::CompiledSchema;
pub use functions_dts::{FunctionPayloadShape, FunctionTypeSpec, generate_functions_dts};

// Re-exported for the emitters: the language-independent machinery lives in
// `client::common` so the Python generator shares the exact same documents.
pub(super) use super::common::{
    SchemaCtx as Ctx, input_base_name, leaf_fields, referenced_named_type,
};
use crate::{Generated, Result};

/// Generate a `TypeScript` client from a compiled schema.
///
/// Returns a map of relative path → file content. Conditional files (`enums.ts`,
/// `inputs.ts`, `mutations.ts`, `relationships.ts`) are present only when the
/// schema has the corresponding definitions; `index.ts` re-exports exactly the
/// files that were emitted.
///
/// # Errors
///
/// Returns an error if the schema cannot be hashed for stamping (see
/// [`crate::client::schema_hash`]).
pub fn generate(schema: &CompiledSchema) -> Result<Generated> {
    let ctx = Ctx::new(schema);
    let hash = super::schema_hash(schema)?;

    let mut files = Generated::new();
    let mut modules: Vec<&str> = Vec::new();
    let add = |files: &mut Generated,
               modules: &mut Vec<&'static str>,
               name: &'static str,
               body: String| {
        files.insert(PathBuf::from(format!("{name}.ts")), stamp(&body, &hash));
        modules.push(name);
    };

    add(&mut files, &mut modules, "types", emit::types(&ctx));

    if !schema.enums.is_empty() {
        add(&mut files, &mut modules, "enums", emit::enums(schema));
    }
    if !schema.input_types.is_empty() {
        add(&mut files, &mut modules, "inputs", emit::inputs(&ctx));
    }
    if !schema.queries.is_empty() {
        add(&mut files, &mut modules, "queries", emit::queries(&ctx));
    }
    if !schema.mutations.is_empty() {
        add(&mut files, &mut modules, "mutations", emit::mutations(&ctx));
    }
    if ctx.has_relationships {
        add(&mut files, &mut modules, "relationships", emit::relationships(schema));
    }

    add(&mut files, &mut modules, "client", runtime::CLIENT_TS.to_string());

    files.insert(PathBuf::from("index.ts"), stamp(&emit::index(&modules), &hash));

    Ok(files)
}

/// Prepend the auto-generated header (with the schema hash) to a file body.
fn stamp(body: &str, hash: &str) -> String {
    format!(
        "// AUTO-GENERATED by fraiseql-codegen. DO NOT EDIT.\n// schema-hash: {hash}\n// fraiseql-codegen: {version}\n\n{body}",
        version = env!("CARGO_PKG_VERSION"),
    )
}

/// Render a sorted `import { ... } from "./module";` block for the given names,
/// grouped by the module that defines each name. Names not defined in any
/// generated module (scalars) are dropped.
fn render_imports(ctx: &Ctx, names: &BTreeSet<&str>, current: &str) -> String {
    let mut by_module: BTreeMap<&'static str, BTreeSet<&str>> = BTreeMap::new();
    for &name in names {
        if let Some(module) = ctx.module_of(name) {
            if module != current {
                by_module.entry(module).or_default().insert(name);
            }
        }
    }

    let mut out = String::new();
    for (module, idents) in by_module {
        let joined = idents.into_iter().collect::<Vec<_>>().join(", ");
        let _ = writeln!(out, "import type {{ {joined} }} from \"./{module}\";");
    }
    out
}
