version: '3.8'

services:
  # PostgreSQL for benchmark
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
      POSTGRES_DB: benchmark_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraiseql"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FraiseQL Benchmark API
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://benchmark:benchmark@postgres:5432/benchmark_db
    depends_on:
      postgres:
        condition: service_healthy
    cpus: 2.0
    mem_limit: 2g

volumes:
  postgres_data:
  grafana_data:
