version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: benchmark_db
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../shared/database/seed-data-small.sql:/docker-entrypoint-initdb.d/02-seed.sql
    ports:
      - "5432:5432"

  hasura:
    image: hasura/graphql-engine:v2.35.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://benchmark:benchmark@postgres:5432/benchmark_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    command:
      - graphql-engine
      - serve
