# GraphQL query depth attack
type: trigger
name: fraiseql/graphql-depth-attack
description: "Detect deeply nested GraphQL queries"
filter: |
  evt.Meta.log_type == 'nginx' &&
  evt.Parsed.request contains '/graphql' &&
  len(evt.Parsed.request) > 5000
blackhole: 30m
labels:
  service: graphql
  type: query_depth
  remediation: true
