//! Tests for the `functions.d.ts` generator.

#![allow(clippy::unwrap_used)] // Reason: test code — fail-loud.

use fraiseql_core::schema::CompiledSchema;

use super::{FunctionPayloadShape, FunctionTypeSpec, generate_functions_dts, pascal_case};

fn specs() -> Vec<FunctionTypeSpec> {
    vec![
        FunctionTypeSpec {
            name:  "notify_approved".to_string(),
            shape: FunctionPayloadShape::Entity {
                entity: Some("Order".to_string()),
            },
        },
        FunctionTypeSpec {
            name:  "nightly_sweep".to_string(),
            shape: FunctionPayloadShape::Cron,
        },
        FunctionTypeSpec {
            name:  "on_webhook".to_string(),
            shape: FunctionPayloadShape::Ingest,
        },
        FunctionTypeSpec {
            name:  "untyped".to_string(),
            shape: FunctionPayloadShape::Entity { entity: None },
        },
    ]
}

#[test]
fn emits_host_ops_and_typed_events() {
    let dts = generate_functions_dts(&CompiledSchema::default(), &specs()).unwrap();

    // Auto-generated stamp + module import of exactly the referenced entity types.
    assert!(dts.contains("AUTO-GENERATED by fraiseql-codegen"), "carries the codegen stamp");
    assert!(
        dts.contains("import type { Order } from \"./types\";"),
        "imports the entity type its payload references"
    );

    // The schema-independent host-op surface, augmenting the ambient Deno namespace
    // from inside a `declare global` (the file is a module).
    assert!(dts.contains("export interface FraiseqlHostOps {"), "declares the host ops");
    assert!(dts.contains("fraiseql_query(graphql: string, variables: string): Promise<string>;"));
    assert!(dts.contains("declare global {"), "host ops augment the ambient Deno namespace");
    assert!(dts.contains("const ops: FraiseqlHostOps;"));

    // Per-function typed events — entity payload references the imported type.
    assert!(dts.contains("export interface NotifyApprovedEvent {"));
    assert!(dts.contains("event_kind: \"insert\" | \"update\" | \"delete\";"));
    assert!(dts.contains("old: Order | null;") && dts.contains("new: Order | null;"));

    // Cron + ingest shapes.
    assert!(
        dts.contains("export interface NightlySweepEvent {") && dts.contains("schedule: string;")
    );
    assert!(
        dts.contains("export interface OnWebhookEvent {")
            && dts.contains("idempotency_key: string;")
    );

    // An unresolved entity falls back to `unknown`, not a dangling type reference.
    assert!(
        dts.contains("export interface UntypedEvent {") && dts.contains("old: unknown | null;")
    );
}

#[test]
fn no_import_line_when_no_entity_payloads() {
    // A schema whose only functions are cron/ingest references no entity type, so the
    // file must not emit an empty `import type {} from "./types"`.
    let cron_only = vec![FunctionTypeSpec {
        name:  "tick".to_string(),
        shape: FunctionPayloadShape::Cron,
    }];
    let dts = generate_functions_dts(&CompiledSchema::default(), &cron_only).unwrap();
    assert!(!dts.contains("import type"), "no import when no entity payloads");
    assert!(
        dts.contains("export interface TickEvent {"),
        "still emits the cron event + host ops"
    );
    assert!(dts.contains("FraiseqlHostOps"));
}

#[test]
fn pascal_case_handles_snake_and_camel() {
    assert_eq!(pascal_case("notify_approved"), "NotifyApproved");
    assert_eq!(pascal_case("syncDeal"), "SyncDeal");
    assert_eq!(pascal_case("on-webhook"), "OnWebhook");
    assert_eq!(pascal_case("X"), "X");
}

/// A `request:query` function's payload is a discriminated union over the fields it
/// answers, with each field's arguments typed from the schema.
///
/// A union even for one field, deliberately: one code path renders one and many, so
/// the shape a guest destructures does not change the day a second query names the
/// same function.
#[test]
fn a_request_query_payload_is_a_discriminated_union_of_its_fields() {
    use fraiseql_core::schema::{ArgumentDefinition, FieldType};

    let argument = |name: &str, arg_type: FieldType, nullable: bool| ArgumentDefinition {
        name: name.to_string(),
        arg_type,
        nullable,
        default_value: None,
        description: None,
        deprecation: None,
    };

    let specs = vec![FunctionTypeSpec {
        name:  "preview_quote".to_string(),
        shape: FunctionPayloadShape::Request {
            fields: vec![
                super::RequestQueryField {
                    name:      "quotePreview".to_string(),
                    arguments: vec![
                        argument("sku", FieldType::String, false),
                        argument("quantity", FieldType::Int, true),
                    ],
                },
                super::RequestQueryField {
                    name:      "bulkQuotePreview".to_string(),
                    arguments: vec![argument(
                        "skus",
                        FieldType::List(Box::new(FieldType::String)),
                        false,
                    )],
                },
            ],
        },
    }];

    let dts = generate_functions_dts(&CompiledSchema::default(), &specs).unwrap();

    assert!(
        dts.contains("export type PreviewQuoteEvent ="),
        "a request payload is a type alias, not an interface: {dts}"
    );
    assert!(
        dts.contains(
            r#"| { field: "quotePreview"; arguments: { sku: string; quantity: number | null } }"#
        ),
        "each member names its field and types its arguments: {dts}"
    );
    assert!(
        dts.contains(r#"| { field: "bulkQuotePreview"; arguments: { skus: string[] } }"#),
        "including the second field the same function answers: {dts}"
    );
}

/// A field with no arguments still gets a member, with an empty argument object.
///
/// The empty object is the point: a guest destructuring `event.arguments` must not
/// have to check whether the key exists, and the compiler's payload builder always
/// emits one.
#[test]
fn a_request_query_field_with_no_arguments_still_gets_a_member() {
    let specs = vec![FunctionTypeSpec {
        name:  "server_time".to_string(),
        shape: FunctionPayloadShape::Request {
            fields: vec![super::RequestQueryField {
                name:      "serverTime".to_string(),
                arguments: vec![],
            }],
        },
    }];

    let dts = generate_functions_dts(&CompiledSchema::default(), &specs).unwrap();
    assert!(
        dts.contains(r#"| { field: "serverTime"; arguments: {  } }"#),
        "an argument-less field still carries the key: {dts}"
    );
}
