//! Auto-generated WASM component bindings for `fraiseql:host`.
//!
//! This module contains the types and traits generated by `wasmtime::component::bindgen!`
//! from the `wit/fraiseql-host.wit` interface definition.

// This is a placeholder for the wasmtime-generated bindings.
// In a real setup, this would be generated by the bindgen! macro,
// but since we're in the trait definition phase, we'll manually define
// the structures that the generated code would create.

use serde::{Deserialize, Serialize};

/// Log level enum matching the WIT definition.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LogLevel {
    /// Debug level.
    Debug,
    /// Info level.
    Info,
    /// Warn level.
    Warn,
    /// Error level.
    Error,
}

/// HTTP response structure matching the WIT definition.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HttpResponse {
    /// HTTP status code.
    pub status: u16,
    /// Response headers.
    pub headers: Vec<(String, String)>,
    /// Response body bytes.
    pub body: Vec<u8>,
}

// Note: In the actual implementation, wasmtime::component::bindgen! would generate
// the following traits and types for each interface:
//
// pub trait Logging: Send {
//     fn log(&mut self, level: LogLevel, message: String) -> wasmtime::Result<()>;
// }
//
// pub trait Context: Send {
//     fn get_event_payload(&mut self) -> wasmtime::Result<String>;
//     fn get_auth_context(&mut self) -> wasmtime::Result<Result<String, String>>;
//     fn get_env_var(&mut self, name: String) -> wasmtime::Result<Option<String>>;
// }
//
// And similar traits for io::*
//
// These would be implemented by the StoreData struct to provide host functionality.
