"""Demo of ORDER BY and GROUP BY with nested fields in FraiseQL.

This example shows how to use ORDER BY and GROUP BY clauses with
nested JSONB fields in PostgreSQL queries generated by FraiseQL.
"""

from psycopg.sql import SQL

from fraiseql.core.translate_query import translate_query


def main():
    """Demonstrate ORDER BY and GROUP BY functionality."""

    # Example 1: Simple ORDER BY with nested fields
    print("=== Example 1: ORDER BY with nested fields ===")
    query1 = """
    {
        id
        name
        profile {
            age
            location {
                city
                country
            }
        }
    }
    """

    result1 = translate_query(
        query=query1,
        table="users",
        typename="User",
        order_by=[
            ("profile.age", "desc"),
            ("profile.location.country", "asc"),
            ("name", "asc"),
        ],
    )

    print("GraphQL Query:")
    print(query1)
    print("\nGenerated SQL:")
    print(result1.as_string(None))
    print()

    # Example 2: GROUP BY with nested fields
    print("=== Example 2: GROUP BY with nested fields ===")
    query2 = """
    {
        country
        city
        userCount
    }
    """

    result2 = translate_query(
        query=query2,
        table="analytics",
        typename="LocationStats",
        group_by=["location.country", "location.city"],
    )

    print("GraphQL Query:")
    print(query2)
    print("\nGenerated SQL:")
    print(result2.as_string(None))
    print()

    # Example 3: Complex query with WHERE, GROUP BY, and ORDER BY
    print("=== Example 3: Complex query with all features ===")
    query3 = """
    {
        browser
        os
        platform
        visitCount
        avgDuration
    }
    """

    where_clause = SQL("data->>'year' = '2024' AND data->'active' = 'true'")

    result3 = translate_query(
        query=query3,
        table="user_sessions",
        typename="SessionStats",
        where_clause=where_clause,
        group_by=["device.browser", "device.os", "device.platform"],
        order_by=[("visitCount", "desc"), ("device.browser", "asc")],
    )

    print("GraphQL Query:")
    print(query3)
    print("\nGenerated SQL:")
    print(result3.as_string(None))
    print()

    # Example 4: Deeply nested fields in ORDER BY and GROUP BY
    print("=== Example 4: Deeply nested fields ===")
    query4 = """
    {
        category
        subcategory
        brand
        totalSales
        avgRating
    }
    """

    result4 = translate_query(
        query=query4,
        table="product_analytics",
        typename="ProductStats",
        where_clause=SQL("data->'metadata'->'year' = '2024'"),
        group_by=[
            "product.category.main",
            "product.category.sub",
            "product.brand.name",
        ],
        order_by=[
            ("product.category.main", "asc"),
            ("totalSales", "desc"),
            ("product.ratings.average", "desc"),
        ],
    )

    print("GraphQL Query:")
    print(query4)
    print("\nGenerated SQL:")
    print(result4.as_string(None))
    print()


if __name__ == "__main__":
    main()
