"""Common domain components for the enterprise blog system.
"""

from .base_classes import (
    AggregateRoot,
    BusinessRule,
    BusinessRuleViolationException,
    DomainEvent,
    DomainException,
    Entity,
    EntityId,
    ValueObject,
)
from .events import (
    CategoryCreatedEvent,
    CommentAddedEvent,
    CommentApprovedEvent,
    CommentRejectedEvent,
    OrganizationCreatedEvent,
    OrganizationSubscriptionChangedEvent,
    PostCreatedEvent,
    PostDeletedEvent,
    PostLikedEvent,
    PostPublishedEvent,
    PostSharedEvent,
    PostUnpublishedEvent,
    PostViewedEvent,
    TagCreatedEvent,
    UserActivatedEvent,
    UserDeactivatedEvent,
    UserRegisteredEvent,
    UserRoleChangedEvent,
)
from .exceptions import (
    BusinessRuleViolationError,
    CommentModerationError,
    DuplicateEntityError,
    EntityNotFoundError,
    InsufficientPermissionsError,
    InvalidCredentialsError,
    InvalidPostStatusTransitionError,
    OrganizationLimitExceededError,
    PostPublishingError,
    SubscriptionTierError,
    UnauthorizedAccessError,
    UserDeactivationError,
    UserRegistrationError,
    ValidationError,
)

__all__ = [
    # Base classes
    "AggregateRoot",
    "BusinessRule",
    "BusinessRuleViolationException",
    "DomainEvent",
    "DomainException",
    "Entity",
    "EntityId",
    "ValueObject",

    # Events
    "CategoryCreatedEvent",
    "CommentAddedEvent",
    "CommentApprovedEvent",
    "CommentRejectedEvent",
    "OrganizationCreatedEvent",
    "OrganizationSubscriptionChangedEvent",
    "PostCreatedEvent",
    "PostDeletedEvent",
    "PostLikedEvent",
    "PostPublishedEvent",
    "PostSharedEvent",
    "PostUnpublishedEvent",
    "PostViewedEvent",
    "TagCreatedEvent",
    "UserActivatedEvent",
    "UserDeactivatedEvent",
    "UserRegisteredEvent",
    "UserRoleChangedEvent",

    # Exceptions
    "BusinessRuleViolationError",
    "CommentModerationError",
    "DuplicateEntityError",
    "EntityNotFoundError",
    "InsufficientPermissionsError",
    "InvalidCredentialsError",
    "InvalidPostStatusTransitionError",
    "OrganizationLimitExceededError",
    "PostPublishingError",
    "SubscriptionTierError",
    "UnauthorizedAccessError",
    "UserDeactivationError",
    "UserRegistrationError",
    "ValidationError",
]
