name: FraiseQL Design Quality Check

on:
  pull_request:
    paths:
      - 'schema.compiled.json'
      - 'schema.json'
      - 'fraiseql.toml'
      - '.github/workflows/design-quality.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'schema.compiled.json'
      - 'schema.json'
      - 'fraiseql.toml'
  workflow_dispatch:
    inputs:
      fail_threshold:
        description: 'Fail if score below this (0-100)'
        required: false
        default: '70'

jobs:
  design-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    services:
      fraiseql-server:
        image: fraiseql/fraiseql-server:latest
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -f http://localhost:8080/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          DATABASE_URL: sqlite::memory:
          FRAISEQL_SCHEMA_PATH: schema.compiled.json
          RUST_LOG: info

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r examples/agents/python/requirements.txt

      - name: Wait for fraiseql-server
        timeout-minutes: 2
        run: |
          set +e
          for i in {1..60}; do
            if curl -f http://localhost:8080/health > /dev/null 2>&1; then
              echo "✅ fraiseql-server is ready"
              exit 0
            fi
            echo "⏳ Waiting for fraiseql-server... ($i/60)"
            sleep 1
          done
          echo "❌ fraiseql-server failed to start"
          exit 1

      - name: Run design audit
        id: audit
        continue-on-error: true
        run: |
          python examples/agents/python/schema_auditor.py \
            schema.compiled.json \
            --api-endpoint http://localhost:8080 \
            --output design-audit-report.html \
            --fail-if-below ${{ github.event.inputs.fail_threshold || '70' }}
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Check results
        if: steps.audit.outcome == 'failure' && steps.audit.outputs.exit_code == '1'
        run: |
          echo "❌ Design quality check failed"
          exit 1

      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: design-audit-report
          path: design-audit-report.html
          retention-days: 30

      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            let comment = '## 📊 Design Quality Audit\n\n';

            if (fs.existsSync('design-audit-report.html')) {
              comment += '✅ Full audit report generated. ';
              comment += '[View in Actions artifacts →](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})';
            } else {
              comment += '⚠️ Could not generate audit report.';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Create check run
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const conclusion = ${{ steps.audit.outcome == 'success' }} ? 'success' : 'failure';

            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Design Quality',
              head_sha: context.sha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'Design Quality Audit',
                summary: 'FraiseQL design quality check',
                text: conclusion === 'success'
                  ? '✅ Design quality check passed'
                  : '❌ Design quality check failed. See artifacts for details.'
              }
            });

      - name: Notify Slack (failure)
        if: failure() && github.event_name == 'push'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "⚠️ Design quality check failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Design Quality Alert"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n${{ github.sha }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.actor }}"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
