# FraiseQL Design Quality Check for GitLab CI
# Add this to your .gitlab-ci.yml

design_quality:
  stage: test
  image: python:3.11

  services:
    - name: fraiseql/fraiseql-server:latest
      alias: fraiseql-server
      variables:
        DATABASE_URL: sqlite::memory:
        FRAISEQL_SCHEMA_PATH: schema.compiled.json
        RUST_LOG: info

  before_script:
    # Install dependencies
    - pip install --upgrade pip
    - pip install -r examples/agents/python/requirements.txt

    # Wait for server to be ready
    - |
      for i in {1..60}; do
        if python -c "import socket; socket.create_connection(('fraiseql-server', 8080), timeout=1)" 2>/dev/null; then
          echo "✅ fraiseql-server is ready"
          break
        fi
        echo "⏳ Waiting for fraiseql-server... ($i/60)"
        sleep 1
      done

  script:
    # Generate HTML report
    - |
      python examples/agents/python/schema_auditor.py \
        schema.compiled.json \
        --api-endpoint http://fraiseql-server:8080 \
        --output design-audit-report.html

    # Check design score (fail if below threshold)
    - |
      python examples/agents/python/schema_auditor.py \
        schema.compiled.json \
        --api-endpoint http://fraiseql-server:8080 \
        --fail-if-below ${DESIGN_QUALITY_THRESHOLD:-70}

    # Generate JSON for parsing
    - |
      python examples/agents/python/schema_auditor.py \
        schema.compiled.json \
        --api-endpoint http://fraiseql-server:8080 \
        --output design-audit-report.json \
        --format json

  artifacts:
    name: design-audit
    paths:
      - design-audit-report.html
      - design-audit-report.json
    reports:
      dotenv: design-audit-metrics.env
    expire_in: 30 days
    when: always

  after_script:
    # Extract metrics for display
    - |
      if [ -f design-audit-report.json ]; then
        python -c "
        import json
        with open('design-audit-report.json') as f:
          data = json.load(f)
        score = data.get('audit_response', {}).get('data', {}).get('overall_score', 0)
        with open('design-audit-metrics.env', 'w') as f:
          f.write(f'DESIGN_SCORE={score}\n')
        print(f'Design Score: {score}/100')
        "
      fi

  variables:
    DESIGN_QUALITY_THRESHOLD: "70"

  allow_failure: false

  only:
    - merge_requests
    - main
    - develop
    - /^feature\/.*/
    - /^hotfix\/.*/

  # Optional: retry on transient failures
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

  # Optional: timeout for the job
  timeout: 10 minutes

  # Merge request rules
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
      when: always
    - when: manual

# Optional: Success notification
notify_design_quality_success:
  stage: .post
  image: curlimages/curl:latest
  script:
    - |
      if [ -f design-audit-metrics.env ]; then
        source design-audit-metrics.env
        curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          -d @- <<EOF
      {
        "text": "✅ Design quality check passed",
        "attachments": [{
          "color": "good",
          "fields": [
            {
              "title": "Repository",
              "value": "$CI_PROJECT_PATH",
              "short": true
            },
            {
              "title": "Branch",
              "value": "$CI_COMMIT_BRANCH",
              "short": true
            },
            {
              "title": "Design Score",
              "value": "$DESIGN_SCORE/100",
              "short": true
            },
            {
              "title": "Pipeline",
              "value": "$CI_PIPELINE_URL",
              "short": false
            }
          ]
        }]
      }
      EOF
      fi
  when: on_success
  only:
    - main
    - merge_requests
  rules:
    - if: '$SLACK_WEBHOOK_URL'
      when: on_success

# Optional: Failure notification
notify_design_quality_failure:
  stage: .post
  image: curlimages/curl:latest
  script:
    - |
      curl -X POST $SLACK_WEBHOOK_URL \
        -H 'Content-type: application/json' \
        -d @- <<EOF
      {
        "text": "❌ Design quality check failed",
        "attachments": [{
          "color": "danger",
          "fields": [
            {
              "title": "Repository",
              "value": "$CI_PROJECT_PATH",
              "short": true
            },
            {
              "title": "Branch",
              "value": "$CI_COMMIT_BRANCH",
              "short": true
            },
            {
              "title": "Commit",
              "value": "$CI_COMMIT_SHA",
              "short": true
            },
            {
              "title": "Author",
              "value": "$CI_COMMIT_AUTHOR",
              "short": true
            },
            {
              "title": "Threshold",
              "value": "$DESIGN_QUALITY_THRESHOLD/100",
              "short": true
            },
            {
              "title": "Details",
              "value": "$CI_PIPELINE_URL",
              "short": false
            }
          ]
        }]
      }
      EOF
  when: on_failure
  only:
    - main
    - merge_requests
  rules:
    - if: '$SLACK_WEBHOOK_URL'
      when: on_failure
