version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: enterprise_patterns_db
      POSTGRES_USER: enterprise_user
      POSTGRES_PASSWORD: enterprise_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enterprise_user -d enterprise_patterns_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://enterprise_user:enterprise_pass@db:5432/enterprise_patterns_db
      - ENV=development
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
