# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.65', require: false
  gem 'rubocop-rspec', '~> 3.0', require: false
  gem 'webmock', '~> 3.23'
end
