name: Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pyright

    - name: Run Ruff linter
      run: ruff check src/

    - name: Check code formatting
      run: ruff format --check src/

    - name: Run type checker
      run: pyright src/
      continue-on-error: true