# DEPRECATED: This workflow is being replaced by quality-gate.yml
# Keeping for backward compatibility during transition
name: Test (Legacy)

on:
  # Reduced scope - quality-gate.yml handles main protection
  push:
    branches: [ feature/*, fix/*, chore/* ]
  pull_request:
    branches: [ dev ]

concurrency:
  group: test-legacy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: fraiseql
          POSTGRES_PASSWORD: fraiseql
          POSTGRES_DB: fraiseql_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: |
        # Use uv for faster and more reliable dependency resolution
        # Install all optional dependencies for comprehensive testing
        uv pip install --system -e ".[dev,all]"

    - name: Run core tests with coverage
      env:
        DATABASE_URL: postgresql://fraiseql:fraiseql@localhost:5432/fraiseql_test
        TEST_DATABASE_URL: postgresql://fraiseql:fraiseql@localhost:5432/fraiseql_test
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: fraiseql
        DB_PASSWORD: fraiseql
      run: |
        # Run core tests first
        pytest tests/ --cov=src/fraiseql --cov-report=xml --cov-report=term-missing -v -m "not blog_simple and not blog_enterprise"

    - name: Run example integration tests
      env:
        DATABASE_URL: postgresql://fraiseql:fraiseql@localhost:5432/fraiseql_test
        TEST_DATABASE_URL: postgresql://fraiseql:fraiseql@localhost:5432/fraiseql_test
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: fraiseql
        DB_PASSWORD: fraiseql
        # Smart dependency management configuration for CI
        FRAISEQL_ENVIRONMENT: ci
        FRAISEQL_AUTO_INSTALL: false
        FRAISEQL_LOG_LEVEL: INFO
      run: |
        # Run example integration tests - provides comprehensive coverage of examples
        pytest tests/integration/examples/ -v --tb=short

    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        flags: unittests
        name: Python-3.13
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
